# -*- coding: utf-8 -*-
"""Unique extra sections for existing guides (append, do not generic-fill)."""
from __future__ import annotations

MORE_DUPLICATES = {
    "android-haziran-guncellemesi-kisilestirme-ve-guvenlik-ozelliklerini-genisletti":
        "android-haziran-drop-guvenlik-ve-kisisellestirme-ozelliklerini-buyuttu",
    "google-i-o-2026-gelistiriciler-icin-ajan-odakli-yeni-donemi-one-cikardi":
        "google-i-o-2026-gelistirici-oturumlarinda-yapay-zeka-araclari-one-cikti",
    "bagimsiz-oyunlardan-haftanin-dikkat-cekenleri":
        "bagimsiz-oyunlar-yaratici-fikirleriyle-one-cikiyor",
    "haftanin-oyun-indirimleri-oyuncularin-ilgisini-cekiyor":
        "haftanin-oyun-firsatlari-ve-ucretsiz-yapimlari-aciklandi",
    "konsol-guncellemeleri-sosyal-ozellikleri-gelistiriyor":
        "konsol-oyunculari-icin-sistem-guncellemesi-yayinlandi",
    "oyuncu-ekipmanlarinda-fiyat-performans-secenekleri-araniyor":
        "oyuncu-ekipmanlarinda-fiyat-performans-secimleri",
    "playstation-plus-haziran-kataloguna-final-fantasy-xvi-ve-sonic-x-shadow-generations-eklendi":
        "playstation-plus-haziran-katalogunda-final-fantasy-xvi-one-cikti",
}


def e(h2a, a, h2b, b, h2c, c, checks, close, **kw):
    d = {"h2a": h2a, "a": a, "h2b": h2b, "b": b, "h2c": h2c, "c": c, "checks": checks, "close": close}
    d.update(kw)
    return d


GUIDE_EXTRA = {
    "akilli-ev-cihazlari-daha-uyumlu-hale-geliyor": e(
        "Matter logosu evdeki Wi-Fi’yi değiştirmez",
        "Kutu üzerindeki Matter yazısı, mevcut modeminin Thread kenarlık yönlendiricisi olduğu anlamına gelmez. 2.4 GHz kalabalık, misafir ağı ve VLAN, ‘uyumlu’ prizi sessizce düşürür. AcarTechs, ilk gece testi önerir: interneti kes, lambanın fiziksel düğmeden yanıp yanmadığına bak. Yanmıyorsa o cihaz ev otomasyonu değil, bulut aboneliğidir. Köprü ayrı satılıyorsa kutu fiyatına ekle; üç köprü, üç uygulama demektir.",
        "Kiralık ev ile müstakil ev aynı alışveriş değildir",
        "Kiralık dairede vida delmeyen fiş ve ampul, taşınırken yanına gelir. Müstakil evde kablo çekilebiliyorsa kablosuz kalabalığı azaltmak uzun vadede daha az arıza üretir. Yaşlı ebeveyn için tek fiziksel düğme hâlâ en iyi arayüzdür; uygulama tek yol olmamalıdır. Kamera ve kilit, aydınlatma ekosistemine bağlanmak zorunda değildir; güvenlik katmanını ayrı tutmak, bir markanın sunucusu düşünce tüm evi kilitlemez.",
        "İlk yıl bütçesi nasıl tutulur?",
        "Aydınlatma ve prizi tek markada tut, kilit ile kamerayı ikinci bir güvenlik katmanı say. Enerji ölçümü, sahne ve ses asistanının üçünü birden ‘hepsi olsun’ dersen arıza yüzeyi büyür. Evdeki eski ampulü Matter’a zorlamak, yeni bir köprü ve ikinci uygulama ister. Bu maliyeti kutu etiketine yazmayan haber, uyumluluk satar, fatura gizler.",
        ["İnternet kesilince lamba yanıyor mu dene", "Köprü fiyatını kutu fiyatına ekle", "IoT cihazını misafir Wi-Fi’de bırakma"],
        "Uyumluluk vitrin cümlesi değil; evdeki ağa, köprüye ve ‘internet gidince ne olur’ testine bağlıdır.",
    ),
    "belgesel-onerileri-teknoloji-ve-doga-meraklilarini-hedefliyor": e(
        "Teknoloji belgeselinde şirket erişimi",
        "Ürün belgeseli çoğu zaman stüdyo erişimiyle çekilir. Anlatıcı ‘yakında her şey değişecek’ diyorsa ilk 10 dakikada tez var mı bak. Yoksa geceyi doldurursun, birikim bırakmazsın. Doğa belgeselinde görüntü kalitesi yüksek, bağlam zayıf kalabilir. ‘İzledim, ne öğrendim?’ cümlesi kurulamıyorsa liste işe yaramamıştır.",
        "Süre süzgeci takvimi bozar",
        "40–55 dakika hafta içi için yeter. Mini dizi 3×45 hafta sonuna bırakılır. 8 bölümlük taahhüt, 1. bölüm yetmiyorsa yazılmaz. Aynı konunun iki belgeselini üst üste izlemek, ikinciyi tekrara çevirir. AcarTechs, haftalık ‘öneri’ başlığını süzgeç sayar; tamamlama yükümlülüğü saymaz.",
        "Çocuk profili ve abonelik katmanı",
        "Doğa belgeseli av ve felaket sahneleri taşıyabilir; yaş etiketini fragmandan okuma. Abonelik katmanında gerçekten var mı, indirme hakkı var mı kontrol et. Offline yoksa yolculuk listesi işe yaramaz. Öğrenci için tek iyi bilim anlatısı, beş yarım kalmış listeden değerlidir.",
        ["İlk 10 dakikada tez yoksa bırak", "Katmanda gerçekten var mı bak", "Aynı konuyu iki kez üst üste izleme"],
        "Belgesel önerisi keşif aracıdır. Tamamını izleme borcu değildir.",
    ),
    "bulut-depolama-servisleri-kapasite-paketlerini-guncelliyor": e(
        "Hangi klasör otomatik yükleniyor?",
        "Telefon rulosu, WhatsApp medyası ve ekran görüntüsü aynı anda açıksa 200 GB aile planı bir yılda daralır. AcarTechs, paket yükseltmeden önce çöpü saymanı ister: tekrar indirilen kurulum, patates kalite screenshot, eski yedek zip. 20 GB temizlik, bir yıl üst katmanı erteleyebilir. Çıkış testi yap: 5 GB’ı başka diske indirmek bir akşamı aşıyorsa o servise kilitlenmişsindir.",
        "Aile planında silme yetkisi",
        "Paylaşım izni net değilse bir kişi diğerinin albümünü boşaltabilir. İki faktör ve yedek kod kâğıtta yoksa hesap ele geçince tek noktadan kayıp olur. Hassas iş dosyasını aynı aile bulutuna koymak, ‘her şey bir yerde’ konforudur; istemci tarafı şifreleme veya ayrı kasa daha dürüst bir ayrımdır.",
        "Tek telefon ile iki bilgisayar",
        "Tek telefon, Wi-Fi’de yükleme: ücretsiz katman + kablo yedeği çoğu kişiyi taşır. Aile ve iki dizüstü: 200 GB–2 TB, paylaşım izni yazılı olan servis. 2 TB’a sıçramak ‘biraz daha yer’ değil ikinci fatura kararıdır. Kampanya, yükleme alışkanlığını değiştirmiyorsa yalnızca faturayı büyütür.",
        ["Otomatik yükleme hangi klasörde açık?", "Ailede kim silebiliyor?", "5 GB çıkış testi yap"],
        "Kapasite kampanyası, depolama alışkanlığını değiştirmiyorsa masraftır.",
    ),
    "bulut-tabanli-calisma-araclari-ekiplerin-is-akisini-degistiriyor": e(
        "Üç ‘son_versiyon.xlsx’ bulutun suçu değildir",
        "Asıl kazanç aynı anda yazmak değil, tek gerçeğin nerede durduğunu bilmektir. İsimlendirme yoksa bulut, dağınıklığı hızlandırır. AcarTechs geçişi ideoloji diye yazmaz. 3 kişilik ekip ve müşteri verisi yoksa geçiş ucuzdur. 15 kişi ve sözleşme varsa izin şeması yazılmadan taşınmaz.",
        "Havalimanında açılmayan sunum",
        "Çevrimdışı paket gerçekten açılıyor mu, uçak modunda dene. Satış sunumu açılamıyorsa araç senin işine göre değildir. İkinci hafta harici paylaşımı varsayılan kapat. Misafir linkine son tarih koy. Silinen dosya çöpte kaç gün duruyor bak; 30 gün değilse kaza silme kalıcıdır.",
        "Kişisel Gmail ile iş dosyası",
        "Muhasebe ve hukuk, müşteri dosyasını kişisel hesapta tutmamalıdır. Kurumsal kirada cihaz kaybında uzaktan silme ve kayıt defteri yoksa ‘ucuz bulut’ gizlilik faturası keser. Bir proje, bir sürücü, bir sohbet kanalı ile başla. İkincisi, izin dağınıklığını gizler.",
        ["Kişisel hesapla iş dosyası paylaşma", "Misafir linkine son tarih", "Uçak modunda açılıyor mu dene"],
        "Bulut ofis, disiplini olan ekibe hız; disiplinsiz ekibe daha hızlı dağınıklık verir.",
    ),
    "dijital-servislerde-yeni-abonelik-paketleri-gundemde": e(
        "Son 30 günde açılmayan satır masraftır",
        "Yeni aile planı, kullanılmayan eski paketi otomatik iptal etmez. Banka ekstresinden tekrarlayan ödemeleri işaretle. Her satıra ‘bu ay kaç saat?’ yaz. 2 saatten az olanı duraklat veya indir. Aile planında tek kişi 4K ve ek üye tutuyorsa plan yanlış kişidedir.",
        "Yıllık ödeme iptali utandırır",
        "Yazılım aboneliğinde yıllık, deneme bitmeden takvim hatırlatması ister. Öğrenci ve yeni mezun için üç ay sonra iş değişince ceza üretebilir. Aylık tutup yoğun ayda açmak, ‘kaçırma’ dilinden ucuzdur. Aynı içeriği iki serviste tutmak, ikinci faturadır.",
        "Yayın evi için 8 saat kuralı",
        "İki platformu aynı anda tutmak, haftalık 8 saatten fazla izleyen ev için rasyoneldir. Altında kalan için ayın yıldızı hangisindeyse o açılır, ay bitince kapanır. Yeni paket haberi listenize satır eklemek zorunda değildir. Çoğu zaman bir satır silmek daha kârlıdır.",
        ["Ekstreden tekrarlayan ödemeyi işaretle", "Deneme bitişini takvime yaz", "Aynı içeriği iki serviste tutma"],
        "Yeni paket, kullanılmayan eski paketi silmez. Sen silersin.",
    ),
    "ev-internetinde-hiz-ve-gecikme-degerleri-daha-fazla-onem-kazaniyor": e(
        "Akşam 21.00 testi",
        "Kabloyla modeme bağlanıp hız testini akşam tekrarla. Kablo iyiyse Wi-Fi kötüdür: kanal, 5 GHz, konum. Kablo da kötüyse paket değil hat veya modem konuşulur. Mesh duvarı sihirle delmez; düğüm ve Ethernet geri dönüşü işe yarar. 1000 Mbps yazısı 12 ms gecikmeli oyunu garanti etmez.",
        "Upload evden çalışanı keser",
        "5 Mbps yükleme, 1080p yayın ve yedek için daralır. Görüntülü arama takılması çoğu evde indirme değil yükleme ve Wi-Fi odasıdır. Oyun + 4K + iki telefon aynı anda ise ‘oyun için ayrı 5 GHz’ ucuz bir ayrımdır. 40 ms üstü ping rekabetçi oyunda cezadır.",
        "Modem şifresi varsayılan kalmasın",
        "Operatör kutusu, varsayılan yönetici şifresiyle bırakılırsa komşu ağın parçası olur. Misafir ağı IoT ve işi ayırır. Paket yükseltmeden önce bu üç katmanı ayır: binaya gelen hat, modem, odadaki kablosuz. Hız paketi, evin akşam gerçeğini ölçmeden alınan tahmindir.",
        ["Akşam kablo testi yapmadan paket değiştirme", "Modem şifresini değiştir", "Oyuna ayrı 5 GHz dene"],
        "Mbps reklamı, akşam saati ve ping kadar evin gerçeği değildir.",
    ),
    "giyilebilir-teknolojiler-saglik-takibinde-daha-iddiali": e(
        "Tek kötü gece paniği",
        "Uyku skoru gece 3’te bakılan telefona göre savrulur. Oksijen ölçümü soğuk parmakta ve hareket halinde gürültülüdür. Nabız kayış ve terle değişir. AcarTechs, tek sapmayı değil 14 günlük eğilimi okumanı ister. Kırmızı uyarıda uygulama değil hekim konuşur. Saat teşhis koymaz.",
        "Pil ve veri ülkesi",
        "Her gece şarj edilen saat uyku takibini yarım bırakır. 5–7 gün giden, daha az özellikli model, düzenli kullanımda ‘daha iddialı’ modelden fazla iş üretir. Verinin telefonda hangi ülkeye gittiği, sağlık vaadinden ayrı gizlilik kararıdır. Sporcu için GPS ve tempo, sağlık kartından değerlidir.",
        "Kime alınır?",
        "Adım ve yürüyüş hatırlatması çoğu insanda işe yarar. Kalp ritmi uyarıları, aile öyküsü olan ve hekimin ‘takip et’ dediği kişiye ek göz olabilir. Kayışı parmak sığacak kadar sık. Kutudaki tıbbi dil ile gerçek kullanım arasına çizgi çekmeyen haber, cihazı doktor yerine koyar.",
        ["14 günlük eğilimi oku, tek geceyi değil", "Kayışı doğru sık", "Veri bölgesine bak"],
        "Saat aynadır. Teşhis koyan cam değildir.",
    ),
    "kablosuz-kulakliklarda-gurultu-engelleme-ozellikleri-gelisiyor": e(
        "ANC her gürültüyü silmez",
        "Uçak ve metroda sürekli düşük frekans vardır; iyi ANC burada parlar. Açık ofiste insan sesi kalır. Koşuda rüzgâr mikrofonları şaşırtır. ‘AI ses modu’ bazen kendi nefesini büyütür. AcarTechs ANC’yi tek özellik diye satmaz. Kullanım yeri, uç bedeni ve şeffaf mod kalitesi karar verir.",
        "Yanlış silikon uç pahalı ANC’yi boşa çıkarır",
        "Üç saatlik konfor, sürücü milimetresinden önce gelir. Kulak içi, yastık bedeniyle ANC’nin yarısını halleder. Şeffaf mod kasa gişesinde ve bisiklette güvenliktir. Kaçak ses kütüphanede komşu düşmanıdır. ANC’yi sokakta varsayılan açmak, araba kornasını geç duyurur.",
        "Çift cihaz ve uçak pili",
        "İş laptop + telefon için hızlı geçiş yoksa ‘pro’ etiket boşa çıkar. Kılıf olmadan 4 saat uçak için yetmeyebilir. Tek telefon kullanıcısı için uygulama şartı ikinci hesap demektir. Gişeden önce şeffaf modu dene; denemeden ‘en iyi ANC’ almak, ofis için uçak kulaklığı almaktır.",
        ["Silikon uç bedenini dene", "Sokakta ANC’yi varsayılan açma", "Şeffaf modu gişeden önce test et"],
        "Gürültü engelleme doğru yerde konfor, yanlış yerde izolasyon ve tehlike üretir.",
    ),
    "kucuk-isletmeler-yapay-zeka-ile-otomasyon-firsatlarini-arastiriyor": e(
        "İlk bot muhasebeyi hedeflemesin",
        "4 kişilik dükkânın sorunu çok ajanlı orkestrasyon değildir. WhatsApp’ta 40 kez sorulan fiyat, randevu ve fatura kalemi tekrarıdır. AcarTechs ilk 30 günü tek işe bağlar: en çok tekrarlanan müşteri sorusunu yanıt taslağına çevir. İkinci 30 gün: randevu veya sipariş formunu insansız al. Muhasebe ve hukuki metin insan onayı olmadan modele bırakılmaz.",
        "Müşteri verisini kişisel hesaba yapıştırma",
        "KVKK ve müşteri güveni, ‘sınırsız asistan’ paketinden önce gelir. Personel Excel biliyorsa hazır tablo + e-posta kuralı, ilk yapay zekâ faturasından ucuzdur. Restoran, klinik randevusu ve kargo sorusu iyi adaydır. Uyarlama üretim, fiyat teklifi ve şikâyet yönetimi kötü adaydır; tonda hata pahalıdır.",
        "Kullanılmayan koltuk",
        "Aylık sınırsız paket, kullanılmayan lisans gibi durur. Yanıtı yayınlamadan insan okusun. İlk ay tek süreç seç. ‘Ajan’ slaytı, küçük işletmenin faturasını şişirir; tekrarlayan cümleyi yok etmek ise gerçek iştir.",
        ["Müşteri verisini kişisel modele yapıştırma", "İlk ay tek süreç", "Yayın öncesi insan oku"],
        "Otomasyon işi yok etmez; aynı cümleyi 40 kez yazmayı yok eder.",
    ),
    "mobil-uygulama-gelistirmede-performans-odakli-yeni-yaklasimlar": e(
        "Orta segment Android vitrin iPhone’dan dürüsttür",
        "Soğuk açılışta tüm SDK’ları ayağa kaldırmak ilk kareyi geciktirir. Analitik ve reklam SDK’sı ağ ve pilin görünmeyen faturasıdır. AcarTechs performansı pazarlama sürümü değil üç ölçüte bağlar: soğuk açılış, kare süresi, ağ suyu. Emülatörden önce gerçek cihaz.",
        "Ürün yöneticisinin animasyon talebi",
        "3 GB RAM’li telefonda kare cezasıdır. Performans bütçesi özellik listesi kadar net yazılmalıdır. Görseli WebP/AVIF ve doğru boyutta yayın. ‘Her olay’ analitiği yerine karar veren olayları ölç. Isınan cihazı ‘kullanıcı şarjı bitmiş’ diye kapatma.",
        "İlk ekrana lazım olmayan işi ertele",
        "Yeni framework soğuk açılışı tek başına düzeltmez. Kullanıcı beyaz ekran, kaydırırken takılma ve 10 dakikada ısınan telefon görür. 3 saniye kuralı, SDK’yı ilk kareden sonra yüklemek ve orta segment cihazda test, vitrin FPS’inden değerlidir.",
        ["Soğuk açılışı 3 saniyenin altında tut", "SDK’yı ilk kareden sonra yükle", "Orta segment cihazda dene"],
        "Performans yeni araç duyurusu değil; kullanıcının elinde kalan sıcaklıktır.",
    ),
    "sosyal-medya-uygulamalarinda-guvenlik-ozellikleri-artiyor": e(
        "Varsayılan hâlâ herkese açıktır",
        "Yeni kilit kapalı kutu olarak gelir. AcarTechs özelliği övmek yerine hesabı ele geçiren senaryoyu merkeze alır: tekrar kullanılan şifre, SMS 2FA, eski oturum, herkese açık konum. Çocuk hesabında ‘bana mesaj atabilenler’ arkadaş-arkadaşı bile geniş olabilir.",
        "Bu hafta yapılacaklar",
        "Şifre yöneticisi, uygulama 2FA (SMS değil), tanıdık olmayan cihazı oturum listesinden at. Konum ve yüz etiketini kapat. Eski e-posta kurtarma adresini güncelle. 2019 tarihli bağlı oyunu sil. Yeni ‘güvenli klasör’ yedek kod kâğıtta yoksa seni kilitleyebilir.",
        "Öfke anında hesap silmek arşivi yakar",
        "Veri indirme 48 saat sürebilir. İş mailiyle açılan hesap kişisel fotoğrafla karışınca işveren araması üretir. Güvenlik özelliği açılmayan anahtardır. Varsayılanı değiştirmeyen duyuru süslemedir.",
        ["SMS yerine uygulama 2FA", "Herkese açık konum kapat", "Bağlı uygulamaları yılda bir buda"],
        "Yeni kilit, varsayılanı kapatmazsan özellik değildir.",
    ),
    "video-uretme-yapay-zekalari-icerik-ureticilerin-radarinda": e(
        "5 saniyelik vitrin 40 saniyeyi kanıtlamaz",
        "Kesitler parlak, el ve yazı hâlâ bozuktur. AcarTechs bu araçları film stüdyosu diye yazmaz. Kısa döngü, B-roll ve fikir taslağı için işe yarar. Ana anlatı ve yüz sürekliliği hâlâ pahalı emektir. Yazıyı modele bırakma; sonradan kapla.",
        "Telif ve müşteri yüzü",
        "İzinsiz yüz ve logo ‘hızlı içerik’ faturasını hukuka çevirir. Ses, görüntüden daha ucuz ve inandırıcıdır: kendi sesin + sade B-roll, tam sentetik karakterden az risklidir. Ajans ‘sınırsız video’ satarken revizyon hakkını saklar. Prompt’u 40 kez döndürmek çekim gününden uzun sürebilir.",
        "Net 15 saniye parlar",
        "Belirsiz 3 dakikada dağılır. İlk 3 saniyede okunmayan yazı Reels/TikTok’ta ölür. 5 saniyelik vitrini 40 saniyeye uzatmadan yayınlama. Araç, senaryosu net kısa kesitte değerlidir; yönetmen koltuğu henüz kiralık değildir.",
        ["Yüz ve logo izni olmadan müşteri filmi yapma", "Yazıyı modele bırakma", "Vitrini uzatmadan yayınlama"],
        "Yapay zekâ video taslak ve dolgu aracıdır. Yönetmen değildir.",
    ),
    "yerli-girisimler-yapay-zeka-destekli-cozumler-gelistiriyor": e(
        "Yerli olmak verinin Türkiye’de kaldığı anlamına gelmez",
        "Alıcıda üç soru yeter: veri nerede duruyor, model hata yapınca kim imzalıyor, iptalde veri geri geliyor mu? AcarTechs duyurudaki isim listesini tekrar etmez. Kamu ve sağlık komşuluğunda dil ve sunucu konumu şartnamedir. Perakendede chatbot çoğu zaman SSS sayfasının pahalı halidir.",
        "Demo sizin fatura PDF’inizle çalışsın",
        "Stüdyo verisiyle çalışan demo, üretimde kırılır. İnsan onayı olmayan otomatik e-posta müşteri kaybettirir. Fiyat token değil koltuk ve destek saatiyle konuşulsun. Çıkış: CSV/JSON dump 7 günde gelmiyorsa kilitlenirsiniz.",
        "Kurucu için ilk müşteri referansı",
        "Slayttaki ‘büyük model’ cümlesinden değerlidir. Modelin kimin API’si olduğu şeffaf değilse yerli katman yalnızca arayüz olabilir. Etiket çözüm değildir; sorunu yerelde çözerse değerlidir.",
        ["Veri bölgesini sözleşmeye yaz", "Hata sorumlusu insan olsun", "İptalde veri iadesi madde olsun"],
        "Yerli girişim, sorunu yerelde çözerse değerlidir. Etiket değildir.",
    ),
    "bilim-kurgu-filmi-ilk-fragmaniyla-dikkat-cekti": e(
        "Ses kapalı bir kez, açık bir kez",
        "Ses kapalı kompozisyon, açıkken müzik hilesini ele verir. 90 saniyelik kesit 130 dakikalık ritmi kanıtlamaz. Erken fragman henüz kurgusu bitmemiş sahne taşır. Renk ve ses son hali değildir. ‘İlk bakış’ ile nihai fragman aynı ürün değildir.",
        "Tarih pencereyse bilet bağlama",
        "Yıl mı mevsim mi bak. Çıkış tarihi pencereyse ön satışa para kitleme. Benzer filmle kıyas ‘aynı yönetmen’ cümlesine sıkışmasın; çekim ölçeği değişmiş olabilir. Çocuk profilinde yaş etiketi fragmanın değil filmin sınırı olabilir.",
        "Ton, yüz, tarih",
        "AcarTechs fragmanı üç katmanda okur: korku/macera/politika, yıldız mı fikir mi satılıyor, tarih net mi. Efekt karesini hikâye sanma. İkinci fragmanı beklemek, ilk 90 saniyeye bütçe bağlamaktan ucuzdur.",
        ["Tarih pencereyse takvime belirsiz yaz", "Efekt karesini hikâye sanma", "İkinci fragmanı bekle"],
        "Fragman davettir. Sözleşme değildir.",
    ),
    "yeni-film-ve-dizi-takvimi-izleyiciler-icin-hareketli-geciyor": e(
        "Ayda 2 başlık",
        "Aynı hafta 12 prömiyer, sizin 6 saatinizi 12’ye bölmez. Pazartesi bu ay bitecek tek dizi seç. Cuma tek film. Üçüncü başlık istek listesidir. Top 10 zevkin değil o ülkenin tıklamasıdır. Belgesel ve komedi aynı akşam birbirini öldürür.",
        "Aboneliği o ayın iki başlığı için aç",
        "Bitince kapatmak yıl boyu tutmaktan ucuz olabilir. Çocuklu evde yaş etiketi ve bölüm süresi kritik beğeniden önce gelir. Spoiler başlıklı kare takvim zevkini çalar. Listeyi resmi uygulama sayfasından, kareyi değil başlığı okuyarak tut.",
        "Platformlar aynı yapımı farklı haftada öne çıkarır",
        "AcarTechs ‘her şeyi tek sayfada topladık’ listesini yeniden dizmez. Evdeki gerçek süreye 2 film veya 1 dizi sığar. Takvim haberi akşamınızı doldurmak zorunda değildir. Elemek izlemektir.",
        ["Ayda 2 başlık", "Top 10’u zevk sanma", "Yaş etiketini fragmandan oku"],
        "Takvim yığını sizin 6 saatiniz değildir. Süzgeçtir.",
    ),
    "yapay-zeka-destekli-arama-motorlari-klasik-aramayi-zorluyor": e(
        "Akıcı cevap doğrulanmış cevap değildir",
        "Model emin duruşla eski tarihi birleştirebilir. ‘2024’te kalktı’ dediği özellik 2026’da geri gelmiş olabilir. Tarih ve resmi belge yoksa özet taslaktır. Tarif, kod iskeleti ve ‘şu terim ne’ için işe yarar. Hukuk, sağlık ve güncel fiyat için asıl sayfaya git.",
        "Cevabın altındaki linke tıkla",
        "İki kaynak çelişiyorsa üçüncüyü aç. Ödev, haber, müşteri notunda yapay zekâ cümlesini olduğu gibi yapıştırma. Şirket içi metni tüketici arama kutusuna yapıştırma. Klasik arama nadir hata kodu ve uzun PDF için hâlâ iyidir.",
        "Girişte dakikayı kısaltır, dipnotu silmez",
        "AcarTechs bu kutuyu ansiklopedi diye kullanmaz. Yeni arama daha az tıklama vaat eder. Sorumluluk hâlâ tıklayanındır.",
        ["Tarihi resmi sayfadan doğrula", "Sağlık/hukuk özetini karar sanma", "Şirket metnini kutuya yapıştırma"],
        "Özet, kaynak linki ve tarih yoksa taslaktır.",
    ),
    "api-kullaniminda-hiz-ve-guvenilirlik-neden-onemli": e(
        "Demo milisaniyesi fatura günündeki p95 değildir",
        "Üretimde yoran mutlu yol değil; 429, 5xx ve 1.8 saniyelik kuyruktur. Tek bölge kullanıcılarınızın uzağındaysa TTFB şişer. Retry körse kesintide kendinizi DDoS’larsınız. Gizli anahtar mobil uygulamada ise kota başkasının olur.",
        "Statü sayfası ve 90 gün kesinti",
        "SLA cümlesi değil kredi nasıl işliyor bak. Webhook imzası ve idempotency yoksa çift tahsilat sizde kalır. Fiyat ‘bin istek’ değil sizin tepe saatinizle çarpılsın. Küçük ekip için yönetilen kuyruk kendi retry yazmaktan ucuzdur.",
        "Anahtarı istemciye gömme",
        "p95 ölç, ortalamayı değil. Retry’e jitter koy. Büyük ekip için çok sağlayıcı, tek sağlayıcı indiriminden az uykusuzluk verebilir. API slayttaki milisaniye değil fatura günündeki hata yüzdesidir.",
        ["Anahtarı istemciye gömme", "p95 ölç", "Retry’e jitter koy"],
        "API seçimi p95, kota ve hata bütçesidir. Demo değildir.",
    ),
    "elektrikli-araclarda-sarj-altyapisi-rekabeti-hizlandi": e(
        "Yoldaki 350 kW, binadaki 11 kW kadar günlük değildir",
        "Sürücü günü evde gece, işte 8 saat ve ayda iki kez yol koridorudur. Apartmanda priz yoksa hızlı istasyon kahraman değil zorunluluktur. İş yeri 11–22 kW veriyorsa ev yatırımı ertelenebilir. Yol: koridor yoğunluğu, ödeme uygulaması ve arızalı soket oranı kW’dan önemlidir.",
        "Soğuk ve otoyol katalog menzilini keser",
        "Yüzde 20–30 koy. Batarya boyutu evde 7 kW ile geceyi doldurur mu bak. İkinci el elektrikli, şarj geçmişi ve batarya raporu olmadan ucuz kilometre değildir. Şehir içi ikinci araç için küçük batarya + ev prizi, büyük batarya + istasyon kuyruğundan sakin bir hayattır.",
        "Apartman yönetimine sormadan sipariş",
        "Priz yoksa aracı avludaki kabloya mahkûm edersin. Yol uygulamasını indirmeden ilk otoyola çıkma. Şarj altyapısı panodaki kW değil sizin gecenizin prizidir.",
        ["Yönetime priz sor", "Soğukta menzile %20 koy", "Yol uygulamasını önceden kur"],
        "İstasyon sayısı, ev prizin yoksa günlük hayat değildir.",
    ),
    "ekran-teknolojilerinde-parlaklik-ve-enerji-verimliligi-yarisi": e(
        "2000 nit perdeli odada göz yorar",
        "Mağaza ışığı evdeki akşam lambasından farklıdır. HDR içerik yoksa parlaklık yarışı logo ve menü yakıcılığıdır. OLED karanlık sahnede siyahı, Mini-LED gündüz salonunda parlaklığı tutar. İkisi de ‘en iyi’ değildir. Oyun monitöründe 1 ms ve Hz HDR’dan önce gelebilir.",
        "Vitrin modunu evde kapat",
        "Mağaza ‘canlı’ profili evde abartılıdır. Film için film, oyun için oyun profili. Tek dinamik profil her ikisini de bozar. Otomatik parlaklık gece elektrik ve OLED iz bırakmayı azaltır; kapatıp 100’e kilitlemek paneli yer. Yansıma nit kadar şikâyettir.",
        "Odayı akşam ziyaret et",
        "Oturduğun yerden pencereye bakış. Mat ekran ofiste okunur, parlak film karesinden vazgeçirir. Nit’e prim, HDR içerik ve oda ışığı yoksa boşa gider.",
        ["Odayı akşam gör", "HDR yoksa nit’e prim verme", "Vitrin modunu kapat"],
        "Parlaklık odanıza göre araçtır. Katalog rekoru değildir.",
    ),
    "gorsel-uretme-araclari-tasarim-surecini-degistiriyor": e(
        "İyi prompt marka kılavuzunun yerine geçmez",
        "Moodboard dakikaya iner. Baskı dosyası, dieline ve yüz sürekliliği hâlâ insan işidir. Ünlü yüz, korunan karakter ve rakip logo ‘ilham’ diye geçmez. Hakki temiz stok, belirsiz model çıktısından az risklidir.",
        "İş akışı dört adım",
        "Metin brief, 8–12 taslak, insanın 2 taneyi düzeltmesi, tipografi ve gerçek ürün fotoğrafı. Modeli son kareye kadar zorlamak 3D ve çekimden uzun sürebilir. Kapak için 1:1 ve 16:9’u ayrı üret; kırmak yüzü yer. ‘Bu görseli kim onayladı?’ yoksa gece yayını markayı yakar.",
        "Onay kutusunu araç işaretlemez",
        "Editör işaretler. Taslağı son ürün sanma. Tipografiyi modele bırakma. Görsel üretici moodboard motorudur. Sanat yönetmeni koltuğuna oturmaz.",
        ["Yüz ve logo izni", "Taslağı son ürün sanma", "Tipografiyi modele bırakma"],
        "Araç taslak katmanındadır. Marka kılavuzu hâlâ insandadır.",
    ),
    "kult-serinin-devam-filmi-icin-hazirliklar-basladi": e(
        "Geliştirme çekim değildir",
        "Çekim vizyon tarihi değildir. Stüdyo ‘üzerinde çalışıyoruz’ deyince bilet ve merch bağlama. Kadro sızıntısı anlaşma değildir. Yönetmen değişimi tonu sıfırlar. Resmi hesap ve sendika çekim bildirimi yoksa hazırlık bir yıl sürebilir.",
        "Nostalji 2026 temposuna uymayabilir",
        "İlk 10 dakikalık sızıntıyı tüm film sanma. Kitap uyarlamasında yazarın adı yeşil ışık değildir. Ön satış vizyon yılı netleşmeden açılırsa stüdyo nakit ister, siz tarih kilitlersiniz. Tarih kayarsa otel iptali sizin riskinizdir.",
        "Üç mertebe",
        "Geliştirme, çekim, vizyon. Birinci mertebede bütçe bağlanmaz. Devam filmi haberi anıdır. Bilet tarihtir.",
        ["Mertebeyi yaz", "Kadro sızıntısını anlaşma sanma", "Ön satışı yıl netleşmeden bağlama"],
        "‘Hazırlık başladı’ cümlesi bilet tarihi değildir.",
    ),
    "yayin-platformlari-yaz-kataloglarini-guncelliyor": e(
        "Aynı yaz üç platformun en iyi yazı olamaz",
        "Üç aboneliği birden tutmak, tatilde günde 3 saat izleyen ev için makuldür. Diğerleri için ayın yıldızı hangisindeyse o açılır. Çocuklu evde yaz animasyon ve aile filmidir; yetişkin dizi ikinci plandadır. Spor yazı ayrı faturadır.",
        "30 gün kuralı",
        "Ayın 1’i: bu ay bitecek tek dizi veya 3 film yaz. Ayın 25’i: bitmediyse uzatma, gelecek aya kaydır. İndirimli yıllık yazın üç aylık yoğunluğu için pahalı kilit olabilir. Offline indirme köy ve uçak için katalogdan önemlidir.",
        "İndirme hakkı kısıtlı hesap",
        "Yaz kataloğu zengin olsa da yolda işe yaramaz. Çocuk listesini ayrı tut. Yıllık taahhüdü yaz indirimine bağlama. Yaz kataloğu sizin 30 gününüzdür, stüdyonun vitrini değildir.",
        ["Ayda tek platform", "Çocuk listesini ayrı tut", "Yıllık taahhüdü yaza bağlama"],
        "Yaz listesi, 30 günlük izleme bütçesidir. Yığın değildir.",
    ),
    "teknoloji-gundeminde-bugun-one-cikan-basliklar": e(
        "20 maddelik özet hiçbiri okunmayan özettir",
        "AcarTechs günlük süzgeci: cihazını veya faturanı değiştiren, resmi kaynağı olan, bu hafta karar isteyen. Sızıntı, stok fotoğrafı ve ‘olabilir’ fiili üçüncü kova değildir. Onlar istek listesidir. Kaynağı resmi olmayanı güne yazma.",
        "Sabah 8 dakika",
        "Resmi blog + bir analiz. Öğle: sızıntı yok. Akşam: yarın karar vereceğin tek başlık. Bu ritim 40 sekmeli gündemden az kaygı üretir. Yatırımcı, geliştirici ve tüketici aynı gündemi okumaz.",
        "Kime yazıldığını başta söyle",
        "Geliştirici API ve kota, tüketici fiyat ve tarih, yönetici risk bakar. Aynı cümle üçüne hizmet etmez. Gündem her şeyi bilmek değil yarın neyi değiştireceğini bilmektir.",
        ["Kaynağı resmi olmayanı güne yazma", "Sızıntıyı takvime işleme", "Günde 3 başlık"],
        "Gündem süzgecidir. Yığın değildir.",
    ),
    "verimlilik-uygulamalari-gunluk-planlamayi-kolaylastiriyor": e(
        "Beş uygulama hiçbiri güncellenmeyen listedir",
        "Sorun uygulama değil listenin üç yerde durmasıdır. Görevler bir yerde, takvim bir yerde, dosya bir yerde. Kişisel işte basit liste yeter. 5 kişilik ekipte durum alanı olmadan sohbet dağılır. 30 kişide araç proje olur; o ölçek bu yazının dışı.",
        "30 dakikada taşıyamıyorsan araç ağırdır",
        "Bildirimleri sessize al; her onay maili planı böler. Cuma 15 dakika arşiv yoksa kanban mezarlığıdır. Öğrenci için ders + teslim, iş için müşteri + son gün. İkisini aynı tahtada karıştırmak akşamı işe çevirir.",
        "Tek görev kaynağı",
        "Yeni görünüm her yıl çıkar. Siz uygulamayı planlarsınız. Uygulama sizi planlamaz.",
        ["Tek görev kaynağı", "Bildirimleri buda", "Cuma 15 dakika arşiv"],
        "Verimlilik uygulaması özellik yarışı değil tek sistem kuralıdır.",
    ),
    "yapay-zeka-araclari-is-dunyasinda-yeni-verimlilik-donemi-baslatti": e(
        "Taslak 10 dakikaya iner, hukuki onay 10 gündür",
        "Masada görülen: e-posta taslağı, toplantı özeti, kod iskeleti hızlanır. Karar, müşteri taahhüdü ve rakamın doğruluğu hızlanmaz. Müşteri sözleşmesini tüketici modele yapıştırmak NDA ihlalidir. Şirket kirası ve bölgesel sunucu yoksa herkesin ChatGPT’si resmi politika olamaz.",
        "İlk 30 gün",
        "İzinli araç, izinli veri, insan onayı. Pazarlama taslağı evet; fiyat teklifi ve sağlık/hukuk hayır. Ölçüm: taslak süresi düştü mü, revizyon arttı mı? İkincisi arttıysa model stajyer gibi her cümleyi yeniden yazdırıyordur. ‘Kullanın’ demek gizli veriyi modele dökmeye davettir.",
        "Eğitim lisans kadar önemlidir",
        "Yönetici için politika cümlesi yoksa araç varsayılanı aleyhinize işler. Verimlilik dakikayı kısaltır. Sorumluluğu kısaltmaz.",
        ["Müşteri metnini tüketici modele yapıştırma", "Onaysız gönderim yok", "Taslak ve revizyonu birlikte ölç"],
        "Ajan slaytı, onay yavaşlığını silmez.",
    ),
    "teknoloji-alisverisinde-garanti-ve-servis-destegi-neden-onemli": e(
        "İki yıl yazısı kapıdaki servis yoksa kâğıttır",
        "1500 TL indirim, arıza günü kargo ve ‘ithalatçı biz değiliz’ ile geri ister. Gri ithal, yurt dışı kutu ve pazar yeri satıcısı resmi distribütörden ucuzdur. Ekran ve batarya arızasında fark yeni cihaz fiyatına yaklaşır. Faturada unvan, IMEI/seri, yetkili servis listesi.",
        "Elden ‘açılmamış kutu’ fotoğrafı kanıt değildir",
        "Uzatılmış garanti ekran çizigini kapsamıyorsa ayrı satılan cam kadar işe yaramaz. Laptop ve TV’de yerinde servis kargo riskini keser. Kulaklıkta swap politikası tamirden değerlidir. Faturayı PDF sakla.",
        "Kampanya kasa anıdır",
        "Garanti 14. aydır. Servis ilini yaz. Gri ithali aynı kutu sanma. AcarTechs teknoloji alışverişini vitrin değil servis haritası olarak görür.",
        ["Distribütör ve servis ilini yaz", "Faturayı PDF sakla", "Gri ithali aynı kutu sanma"],
        "Kutu fiyatından önce servis ağı gelir.",
    ),
    "yeni-nesil-telefon-bataryalari-daha-uzun-omur-hedefliyor": e(
        "6000 mAh her gün 100’e 120W ile doluyorsa şişer",
        "Hızlı şarj dakikayı kurtarır, kimyayı yer. 80–20 kuralı birçok telefonda yazılımla gelir. Kapalıysa 85’te kesen priz işe yarar. Kılıf içinde 120W ısı tuzağıdır. Ekran 120 Hz ve parlak HDR bataryayı mAh’den hızlı yer.",
        "60 Hz seçeneği seyahatte bir saat kazandırır",
        "Değiştirilebilir batarya yoksa 24 ay sonrası takas fiyatı kararın parçasıdır. Soğukta yüzde 1’den kapanma kapasite değil kalibrasyondur. Tam boşaltıp doldurmak eski ni-cad alışkanlığıdır; bugün işe yaramaz.",
        "Gece 100’e kilitleme",
        "Watt tablosu değil gece prizi alışkanlığı ömrü belirler. Kullanıcı günü 1.5 şarj ve ılık arka kapaktır. Uzun ömür döngü ve ısıdır.",
        ["Gece 100’e kilitleme", "Hızlı şarjı kılıfla yakma", "120 Hz’i dışarıda kıs"],
        "Batarya ömrü mAh rekoru değil döngü ve ısıdır.",
    ),
    "egitimde-yapay-zeka-destekli-calisma-araclari-yayginlasiyor": e(
        "Cevabı yapıştırmak yakalanma riskini kısaltır, öğrenmeyi değil",
        "AcarTechs çizgisi: kavramı sordur, cevabı yazdırma. Model emin duruşla olmayan makale uydurur. Her iddiayı gerçek makalede ara. ‘Bu paragrafı 15 yaş diline çevir’, ‘şu formülü neden böyle’, ‘quiz üret, cevabı sonra göster’ doğru. ‘Bitmiş ödev yaz’ yanlış.",
        "Sınav yazısını modele yazdırmak sınavda boş kalmaktır",
        "Dil öğreniminde konuşma pratiği işe yarar. Veli: hesap okul mailiyle açılsın, sohbet silinsin, kişisel fotoğraf yüklenmesin. Öğretmen: nerede serbest nerede yasak ödev kâğıdında dursun. Politika yoksa araç öğrencilerin aleyhine işler.",
        "Öğretmenin yerine geçmez",
        "Çalışma arkadaşının tembel halidir; siz yönetmezseniz o yönetir. Kaynağı gerçek makalede arayın.",
        ["Kaynağı gerçek makalede ara", "Ödevi yazdırma, açıklattır", "Okul politikasını kâğıda yaz"],
        "Açıklama evet, ödev hayır.",
    ),
    "siber-guvenlik-yamalarini-geciktirmek-buyuk-risk-olusturuyor": e(
        "‘Sonra bakarım’ botnet’in sevdiği cümledir",
        "Ev kullanıcısı ‘ben hedef değilim’ der. Tarayıcı, yönlendirici ve eski eklenti hedef seçmez; tarar. 48 saat kuralı: kritik yama iki gün içinde. Beşli: Windows, telefon OS, tarayıcı, VPN, yönlendirici firmware. Yazıcı ve kamera da ağdadır.",
        "Önce yedek",
        "Sonra OS, sonra tarayıcı. Yönlendiriciyi gece, çünkü kopabilir. Ofiste herkese aynı anda basmak yerine 1 PC ile dene. Yedek aynı ağa bağlı NAS’ta tek kopyaysa yedek değildir. Eski Windows 10 yama almıyorsa bankacılık ve iş maili için ayrı ağda tut veya emekli et.",
        "Antivirüs slaytından önce bu beşli",
        "Yama kahramanlık değildir. Ertelemek başkasının botnet’ine kira vermektir. Yönlendirici şifresini değiştir. Çevrimdışı bir kopya tut.",
        ["48 saat kuralı", "Yönlendirici şifresini değiştir", "Yedek çevrimdışı bir kopya"],
        "Kritik yama iki gün kuralıdır. Korku dili değil sıra listesidir.",
    ),
    "acik-kaynak-projeler-teknoloji-dunyasinda-etkisini-artiriyor": e(
        "GitHub yıldızı güvenlik denetimi değildir",
        "Lisans (MIT/Apache/GPL), son commit, issue yanıtı, tek bakıcı riski. GPL copyleft kapalı ürünü zorlar. MIT atıf ister. Lisansı okumadan npm install, hukukun ‘bilmiyordum’ kabul etmediği yerdir. SBOM veya lockfile olmadan en son sürüm çekme.",
        "Tek bakıcılı paket kritik yolda",
        "Çatal veya ticari destek planı olmadan girmesin. Issue şablonu ve davranış kuralları yoksa PR’ın da havada kalır. Öğrenci için açık kaynak portföydür; yıldız için anlamsız commit spam’i bakıcıyı yorar.",
        "Lockfile’ı commit et",
        "LICENSE dosyasını README’den önce oku. Açık kaynak bedava iş gücü değildir. Bakımı paylaşılmazsa borçtur.",
        ["LICENSE dosyasını oku", "Tek bakıcı riskini yaz", "Lockfile’ı commit et"],
        "Haftalık kütüphane listesi ezberi değil lisans ve bakıcıdır.",
    ),
    "donanim-pazarinda-fiyat-ve-performans-dengesi-degisiyor": e(
        "Vitrindeki FPS 650W eski PSU’da gelmez",
        "1080p monitörde 4K kartına para gömmek denge değildir. Sıra: monitör Hz ve çözünürlük, hedef FPS, işlemci darboğazı, PSU watt ve 80+, kasa hava. Tersi pahalı kartı yavaş bırakır. RAM 32 GB 2026 oyun ve tarayıcı için yeni varsayılandır; 16 GB idaredir.",
        "İkinci el kart madencilik ve hayalet garanti taşır",
        "Faturasız kutu arızada sizin olur. Yeni kartta 3 fan dar kasada ısınır ve kısılır. Ofis PC’sinde iGPU yeter; oyun sloganlı kasa israftır. Sessizlik isteyen evde fan sayısı RGB’den önemlidir.",
        "PSU’yu kartla birlikte hesapla",
        "Fiyat/performans slayttaki FPS değil masadaki watt ve 24. aydır. Faturasız ikinci eli iş PC’sine koyma.",
        ["Önce monitör", "PSU’yu kartla hesapla", "Faturasız ikinci eli işe koyma"],
        "En yeni almak, monitörünüzün çözünürlüğünü yok saymaktır.",
    ),
    "ios-ve-android-arasindaki-farklar-kullanici-deneyiminde-belirginlesiyor": e(
        "Hangisi daha iyi cümlesi evdeki diğer kutuya bağlıdır",
        "Evde Mac ve iPad varsa iPhone az sürtünme üretir. Windows ve ucuz tablet varsa Android. İki kişi iki sistem, fotoğraf köprüsü (Google Fotoğraflar veya iCloud) kurulmadan acıtır. iOS güncelleme süresi ve ikinci el fiyatında öndedir. Android yan yükleme, varsayılan uygulama ve ucuz girişte esnektir.",
        "Onarım ve aile paneli",
        "Parça ve yetkili servis iliniz. APK ihtiyacınız var mı? Çocuk: Family Link / Ekran Süresi hangisini gerçekten kullanacaksınız? Bankacılık bazı uygulamalar eski Android’i keser. Klasör ve USB Android’de rahattır; iOS paylaşımı uygulama içine iter. Ham fotoğraf çeken için bu din farkı kadar büyüktür.",
        "Ekosistemi yaz, logoyu değil",
        "Aile kilidini denemeden alma. Onarım ve ikinci el fiyatına bak. Platform kimlik değil yedek, servis ve evdeki diğer kutudur.",
        ["Ekosistemdeki diğer cihazı yaz", "Onarım ve ikinci el fiyatına bak", "Aile kilidini denemeden alma"],
        "2026’da gerçek fark yedek, yan yükleme ve onarımdır. Logo değildir.",
    ),
    "mini-pc-modelleri-ev-ve-ofis-kullanimi-icin-yayginlasiyor": e(
        "Cep boyu kasa oyun kulesinin watt’ını taşımaz",
        "Ofis, tabela ve hafif montaj için uygundur. AAA oyun ve 4K kurgu nefes darlığı çeker. RAM lehimliyse 16 GB tavan 2026 tarayıcı + toplantı için daralır. NVMe tek yuva yedek disk koymaz. İki HDMI 4K 60 verir; 120 Hz oyun monitörü DisplayPort ister.",
        "Idle watt ve fan, salonda FPS’den önemlidir",
        "VESA montajı masayı boşaltır. Windows lisansı Home mu etiket mi? Ofiste BitLocker ve TPM yazıyor mu bak. Ev sunucusu için düşük watt 7/24 kâr eder. Oyun için mini PC eGPU macerasına kayar; o noktada kule daha dürüsttür.",
        "RAM lehimli mi yuva mı?",
        "Çıkışlar monitörünü tutuyor mu? Mini PC doğru işte sessiz kahraman, yanlış işte ısınan kutudur.",
        ["RAM lehimli mi?", "Idle watt", "Çıkışlar monitörü tutuyor mu?"],
        "Küçük kasa, watt, RAM tavanı ve ekran çıkışıdır. Oyun vaadi değildir.",
    ),
    "telefon-alirken-dikkat-edilmesi-gereken-en-onemli-ozellikler": e(
        "Kamera megapikseli dördüncü sıradır",
        "Sıra: güvenlik güncellemesi taahhüdü, batarya ve şarj, ekran okunabilirliği, servis, sonra kamera. 120 Hz güzeldir, 60 Hz seçeneği yoksa gezi günü yer. IP derecesi lavabo ve yağmur içindir, deniz suyu değildir. 5G kapsama yoksa pil yer.",
        "Bütçe dilimleri",
        "Giriş: 3 yıl yama + sağlam batarya. Orta: 5–7 yıl yama, yeterli kamera. Üst: ikinci el değeri ve tamir parçası. Gri ithal kamera aynı, servis farklıdır. Elden satışta iCloud/Google kilit ve IMEI kayıt. Açılmamış kutu kayıtlı başka TC olabilir.",
        "Yama yılını üretici sayfasından oku",
        "Servis ilini yaz. IMEI’yi faturaya işlet. İyi telefon vitrinde parlayan değil üçüncü yılında hâlâ yama alan telefondur.",
        ["Yama yılını üretici sayfasından oku", "Servis ilini yaz", "IMEI’yi faturaya işlet"],
        "Vitrin karesi 24. aydaki yazılımı göstermez.",
    ),
    "yeni-nesil-dizustu-bilgisayarlar-daha-hafif-ve-guclu-geliyor": e(
        "1.1 kg gövde 400 gram adaptörle çantada 1.5 kg’dır",
        "İnce kasa 28W üstünü kısa süre tutar, sonra kısılır. 30 dakikalık Cinebench değil 2 saatlik toplantı + tarayıcı ısısı. RAM lehimli 16 GB tavan olabilir. SSD tek yuva yedek koymaz. 16:10 ofiste, 16:9 filmde; dokunmatik yansıma ve pil yer.",
        "Kim hangi kasa?",
        "Öğrenci: 1.4 kg altı, 8 saat gerçek, iyi klavye. Ofis: HDMI, USB-A, servis. Üretim: soğutma ve 32 GB. Oyun ince kasa gürültü ve 90 dakika pildir. Menteşe ve klavye ince kasada ilk kırılanlardır; tamir fiyatını sor.",
        "Adaptörü tart",
        "RAM lehimliyse 32 GB düşün. Garanti yerinde mi kargo mu? Hafif dizüstü çantadaki toplam gram ve 2. saatteki fan ile ölçülür.",
        ["Adaptör ağırlığını tart", "RAM lehimliyse 32 GB düşün", "Menteşe tamir fiyatı"],
        "İnce-hafif vaadi şarj aleti, klavye ve RAM tavanıyla tartılır.",
    ),
    "windows-pc-kullanicilari-icin-performans-ipuclari": e(
        "Tema ve oyun modu dolu diski düzeltmez",
        "Üç neden: açılışta 30 program, disk %90, laptop 90 derece. Kayıt defteri temizleyicisi önerme; yedek almadan siler. Başlangıcı Görev Yöneticisi’nden ayıkla. Depolama %20 boş olsun. Güç planı dengeli; en iyi performans fan ve ısıyla kısılır.",
        "Ne zaman donanım?",
        "HDD hâlâ sistem diskine SSD en büyük sıçramadır. 8 GB RAM 2026’da yetmez. 16 GB ofis, 32 GB tarayıcı+VM. GPU 1080p monitör yoksa acil değildir. Sürücü Windows Update + üretici sitesi; rastgele paket sitesi değil.",
        "Malware ve temizleyici",
        "Ana sayfa kaçtıysa reset ve Defender. Temizleyici indirmek ikinci zararlıdır. Hız sihirli ayar değil açılış, boş disk ve nefes alan kasadır.",
        ["Başlangıcı ayıkla", "Diskte %20 boşluk", "Kayıt temizleyici yok"],
        "Yavaşlık üç yerdedir. Yirmi numara listesi değildir.",
    ),
    "ofis-bilgisayari-alirken-nelere-dikkat-edilmeli": e(
        "RGB kasa muhasebe masasında gürültü ve toz üretir",
        "Gerekler: iki ekran çıkışı, TPM 2.0, BitLocker, 3 yıl yerinde servis, sessiz fan. iGPU ofis ve 1080p video için yeter. CAD ve 4K kurgu ayrı listedir. Mini kasa yer kazandırır; genişleme ve toz temizliği zorlaşır.",
        "Toplu alım aynı model aynı BIOS aynı imaj",
        "Karışık kasa yardım masasını öldürür. OEM Windows cihazla ölür; iş değişince kutu lisansı ayrı konuşulur. 20 cihazlık ofiste 1 yedek PSU ve 1 SSD bir günlük duruşu keser. Çalışan dizüstü istiyorsa mini PC + paylaşılan monitör, herkese oyun laptopu dağıtmaktan ucuzdur.",
        "İş istasyonu etiketi gerçek CPU/RAM ihtiyacına bağlıdır",
        "Ofis bilgisayarı vitrin değil sessiz, yönetilir ve 36. ayda hâlâ açılır.",
        ["TPM ve 3 yıl yerinde servis", "İki ekran çıkışı", "Sessiz kasa, RGB değil"],
        "FPS slaytıyla ofis alımı yapılmaz.",
    ),
    "katlanabilir-telefonlarda-2026-rekabeti-hizlandi": e(
        "Açık ekran büyük, kapalı yazılım yarım kalabilir",
        "İç ekran koruyucusu ev tipi cam değildir. Toz menteşede birikir. Uygulamalar hâlâ üst-alt reklam ve video için tam katlanır düzen vermeyebilir. Not ve PDF okuyan, tableti sevmeyen kişiye iç ekran işe yarar. Tek elle yazan ve tek cep isteyene klasik kayrak daha az pişmanlıktır.",
        "İkinci cihaz olarak katlanır az risklidir",
        "Birincil telefon olarak daha pahalı cam faturasıdır. Garanti menteşeyi kapsıyor mu, düşme iç cami kapsıyor mu ayrı maddelerdir. Sigorta primi kasa farkını iki yılda yer. İç cam tamir fiyatını sor.",
        "Uygulamayı açık-kapalı dene",
        "Tozlu ortamda menteşe riski. Unpacked vitrini menteşe ömrü, uygulama uyumu ve cam fiyatıyla okunur.",
        ["İç cam tamir fiyatını sor", "Uygulamayı açık-kapalı dene", "Tozlu ortamda menteşe riski"],
        "Katlanır vitrinde gelecektir. Masada menteşe ve cam faturasıdır.",
    ),
    "android-telefonlarda-dosya-paylasimi-daha-kolay-hale-geliyor": e(
        "Yakındaki cihaz iki markada bazen birbirini görmez",
        "Nearby / Quick Share birleşmeleri işi sadeleştirir. Wi-Fi, Bluetooth ve görünürlük kapalıysa sihir yoktur. Kısa video ve PDF: yakındaki paylaşım. 4 GB ham video: kablo veya bilgisayar. Hassas sözleşme: USB veya şifreli kasa, herkese açık kablosuz değil.",
        "Görünürlüğü kişilerim yap",
        "Misafir ağı iki telefonu ayırabilir. iPhone’a gönderim fotoğraf için en sorunsuz bulut veya kablo olabilir; zorlamak 20 dakika yer. İş telefonunda paylaşımı kapatmak sızıntıyı keser. Çocuk hesabı yakındaki herkesten dosya almamalıdır.",
        "AirDrop cümlesini kopyalama",
        "Hangi yol ne zaman: görünürlük, kablo, hassas dosya. Kolaylık görünürlüğü herkes yapmak zorunda değildir.",
        ["Görünürlük: kişilerim", "Büyük dosya kablo", "Hassas dosya herkese açık paylaşımda değil"],
        "Paylaşım ayarı ve hesap, slogan listesinden önce gelir.",
    ),
    "airdrop-destegine-sahip-tum-android-telefonlar": e(
        "Destekli telefonlar tablosu ayar kapalıysa boştur",
        "Google hesabı, Bluetooth, konum izni ve görünürlük kapalıysa hiçbir liste işe yaramaz. Eski cihaz üretici menüsünde özelliği saklar. İki Android aynı Wi-Fi’de değilse keşif düşer. AcarTechs model ezberi yapmaz.",
        "iPhone köprüsü",
        "Fotoğraf için Google Fotoğraflar veya kablo daha az kavga çıkarır. PDF için e-posta veya mesaj. Zorla AirDrop gibi aramak 15 dakikalık Bluetooth dansıdır. Toplantıda herkese görünür bırakmak yabancı dosya davetidir. İş bitince kapat.",
        "Konum izni keşif içindir",
        "Her zaman açık tutulmak zorunda değildir. AirDrop kelimesi arama tuzakıdır. Ayar ve hesap model listesinden önce gelir.",
        ["Görünürlüğü toplantı bitince kapat", "iPhone için ayrı köprü planla", "Konum iznini sürekli açık tutmak zorunda değilsin"],
        "Liste ezberi değil Quick Share görünürlüğü, hesap ve iPhone köprüsüdür.",
    ),
    "robot-supurge-modellerinde-haritalama-teknolojisi-gelisiyor": e(
        "Güzel harita 2 cm eşiği çıkamayan tekerleği kurtarmaz",
        "Evde halı saçak, eşik, kablo ve uzun saç vardır. Üç test: eşik, saç dolaması, haftalık bakım. LIDAR karanlıkta duvarı görür; siyah halıda düşme sensörü şaşırabilir. Akıllı oda ayırımı kapı eşiği geçilmiyorsa işe yaramaz.",
        "Toz istasyonu gece komşusudur",
        "Filtre ve fırça fiyatını 24 aya yay. Evde çok kablo varsa dikey süpürge daha az küfür ettirir. Ev haritası üretici bulutuna gidiyorsa kamera/mikrofonsuz model tercih edilebilir. Çocuk ve evcil hayvanda fırça kapağı ve düşme sensörü şarttır.",
        "Eşik yüksekliğini ölç",
        "Robot harita uygulaması değil eşiği çıkan ve saçı dolamayan makinedir.",
        ["Eşik yüksekliğini ölç", "Fırça yedek fiyatı", "Harita buluta gidiyor mu?"],
        "LIDAR vaadi eşik, saç ve bakım maliyetidir.",
    ),
    "ssd-fiyatlarindaki-degisim-bilgisayar-toplamayi-etkiliyor": e(
        "7000 MB/s 200 GB arşivde ısınır ve düşer",
        "Bu hafta al paniği TBW’si düşük QLC’yi sistem diskine koydurur. Sistem: daha iyi dayanım ve dürüst DRAM/HMB. Arşiv: kapasite, ısınma, yedek. PCIe 5.0 soğutmasız 70 derecede kısılır. 4.0 iyi soğutmalı günlük kopyada farkı hissettirmez.",
        "1 TB sistem, 2 TB oyun/medya",
        "Tek 4 TB her şeyi koyup yedeksiz yaşamak bir denetici hatasında her şeyi kaybetmektir. 3-2-1: 3 kopya, 2 ortam, 1 dışarıda. Laptop’ta tek yuva varsa dışarıda 2 TB yedek, içerideki fırsat 4 TB’dan değerlidir.",
        "Hız rekoruna soğutmasız inanma",
        "SSD fırsatı yedeksiz kapasite değildir. Dayanım ve ikinci kopyadır.",
        ["TBW ve garanti yılını oku", "Sistem ile arşivi ayır", "Hız rekoruna soğutmasız inanma"],
        "GB/TL haberi vitrin hızı değil TBW, ısı ve yedektir.",
    ),
    "yazilim-testlerinde-otomasyon-kullanimi-artiyor": e(
        "Her tıklamayı kaydetmek bakımı testten pahalı hale getirir",
        "Kırılan şey giriş butonunun CSS sınıfıdır. Otomasyonu giriş, ödeme ve kayıt gibi para kaybettiren yola bağla. Görsel ince ayar ve keşif elle kalır. Flaky test CI’yi yalancı çobana çevirir. Ekip kırmızıyı görmezden gelmeye başlar.",
        "İlk 10 test",
        "Giriş, şifre sıfırlama, ödeme mutlu yolu, stok bitişi, yetkisiz sayfa. Bitti. Renk ve animasyon sonra. Gerçek kart değil sahne ortamı. Üretim kopyasını testçilere açma. Küçük ekipte 10 sağlam test 400 kırılgan kayıttan değerlidir.",
        "Araç değişimi bu 10’u taşımıyorsa geçme",
        "Otomasyon daha çok test değil güvenilen az testtir.",
        ["Para kaybettiren yolu otomatikleştir", "Kırılgan testi sil veya düzelt", "Üretim verisini teste kopyalama"],
        "Otomasyon artıyor cümlesi araç listesi değil kırılgan UI ve değerli yoldur.",
    ),
    "ses-klonlama-teknolojileri-icin-guvenlik-tartismasi": e(
        "30 saniyelik örnek annenizin sesiyle borç isteyebilir",
        "Demo eğlencelidir. Dolandırıcılık da öyledir. Aile için kırmızı çizgi: banka ve acil para talebi telefonda sesle doğrulanmaz. Önceden kararlaştırılmış bir kelime veya görüntülü arama. Rıza olmadan başkasının sesini klonlamak eğlence değil ihlaldir.",
        "İş yerinde sesli asistan",
        "Müşteri kaydı ve çağrı merkezi klonu, sözleşmede rıza ve saklama süresi olmadan kullanılmaz. ‘Bu ses sentetik olabilir’ filigranı her zaman duyulmaz. Aile WhatsApp grubuna şaka klonu, yaşlı akrabaya gerçek gelir.",
        "Ne yapılmaz?",
        "Banka, kargo ve ‘hemen yatır’ senaryosunda sese güvenme. Klon rıza, dolandırıcılık ve ne yapılmaz sorusudur. Eğlenceli demo değildir.",
        ["Para talebini sesten doğrulama", "Ailede önceden kelime kararlaştır", "Başkasının sesini rızasız klonlama"],
        "Ses klonu rıza ve dolandırıcılık konusudur. Demo değildir.",
    ),
    "animasyon-dunyasinda-yeni-proje-duyuruldu": e(
        "Stüdyo adı yaş etiketi değildir",
        "Aynı marka hem okul öncesi hem ergen korku üretebilir. Hedef yaş, bölüm süresi ve platform katmanı duyurudaki logo kadar önemlidir. Fragman neşeli, film karanlık olabilir. Çocuk profilinde otomatik oynatma kapatılmadan ‘yeni proje’ açılmaz.",
        "Hangi platform, hangi tarih penceresi",
        "Sinema + streaming aynı gün ise evde büyük ekran kararı öne alınır. Yalnızca bir platformda ise aboneliği o aya sıkıştır. Devam filmi veya spin-off, ilk filmi bitirmemiş ev için zorunlu değildir. Merch ve bilet, stüdyo tweet’inden önce resmi sayfaya bakılarak bağlanır.",
        "Çocuklu ev için süzgeç",
        "Süre, korku eşiği, dil. Üçü net değilse duyuru istek listesidir, bu akşamın filmi değildir.",
        ["Hedef yaşı resmi sayfadan oku", "Platform katmanını kontrol et", "Otomatik oynatmayı çocuk profilinde kapat"],
        "Animasyon projesi haberi stüdyo, hedef yaş ve platformdur. Logo değildir.",
    ),
    "oyuncu-kadrosu-guclenen-yeni-dram-dizisi-tanitildi": e(
        "Yıldız adı 8 sezon taahhüdü değildir",
        "Showrunner değişimi tonu sıfırlar. Bölüm süresi 42 mi 70 mi, haftalık mı toplu yayın mı bak. Kadro sızıntısı anlaşma değildir. İlk sezon bitmeden ikinci sezon heyecanı, yayın takvimini şişirir.",
        "Spoiler başlığı dizi zevkini çalar",
        "Kadro haberini oyuncu fotoğrafı değil karakter işleviyle oku: yeni yüz hikâyeyi mi taşıyor, yoksa afiş mi dolduruyor? Afiş dolduruyorsa beklemek ucuzdur. Bölüm bağımsızlığı yoksa 10 bölümlük borç yazma.",
        "Bu dizi kimin akşamı?",
        "Haftalık ritmi olan ev ile hafta sonu binge ev aynı diziyi aynı anda tutamaz. Kadro haberi showrunner, süre ve yayın modelidir.",
        ["Showrunner net mi?", "Bölüm süresi ve yayın modeli", "Kadro sızıntısını anlaşma sanma"],
        "Yeni dram dizisi kadro, showrunner ve bölüm süresidir. Afiş değildir.",
    ),
    "teknoloji-alisverisinde-kampanya-donemi-basladi": e(
        "Sepetteki fiyat geçmişi yoksa indirim iddiasıdır",
        "Aynı model 14 gün önceki etiketten bak. Stok ‘son 2 adet’ pazaryerinde her gün yenilenir. Sepete atıp 24 saat beklemek, sahte kuponu ele verir. Kargo eşiği ve iade penceresi kasa farkını yer.",
        "Gri kutu ve pazaryeri satıcısı",
        "Kampanya döneminde sahte fatura ve açılmış kutu artar. IMEI/seri faturada yoksa iade zorlaşır. ‘Yerinde teslim indirimi’ kapıda nakit baskısıdır; fiş ve kutu fotoğrafı o anda alınır. Uzatılmış garanti ekranı kapsamıyorsa ayrı satılan camdır.",
        "İade ve stok tuzağı",
        "Kampanya sepet, fiyat geçmişi ve stok tuzağıdır. Vitrin yüzdesi değildir.",
        ["Fiyat geçmişine bak", "Faturada IMEI/seri", "Sahte kupon için 24 saat bekle"],
        "İndirim dönemi kasa anıdır. Fiyat geçmişi ve iade penceresi karardır.",
    ),
    "populer-dizinin-yeni-sezon-tarihi-aciklandi": e(
        "Pencere tarih değildir",
        "‘Bu sonbahar’ bilet ve izin günü bağlamak için yetmez. Bölge: Türkiye kataloğu ABD tarihinden haftalar sonra gelebilir. Spoiler thumbnail’i açmadan resmi tarih sayfasına bak. İlk bölüm özel gösterim, sezonun geri kalanı aylar sonra olabilir.",
        "Toplu yayın mı haftalık mı",
        "Toplu yayın bir hafta sonunu yer. Haftalık 8 haftalık ritim ister. Çocuklu evde bölüm saati, ‘kritik beğeni’den önce gelir. Önceki sezonu bitirmeden yeni sezon heyecanı, arşiv borçudur.",
        "Takvime belirsiz yaz",
        "Dizi sezon tarihi pencere, bölge ve spoiler süzgecidir. Tweet tarihi değildir.",
        ["Tarih pencereyse belirsiz yaz", "Bölge kataloğunu kontrol et", "Spoiler kareyi açma"],
        "Sezon tarihi net yıl ve bölge olmadan izin günü bağlamaz.",
    ),
    "bilgisayar-bakimi-performansi-nasil-etkiler": e(
        "Toz, termal macun ve kablo üçlüsü",
        "Laptop 90 derece ise önce hava yolu. Kompresör yerine yumuşak fırça ve elektrik süpürgesi dışarıdan. Macunu her yıl değiştirmeyin; 3–4 yıl veya gerçekten yüksek sıcaklıkta. Kötü sürümlü ‘performans paketi’ sürücü bozar. Kablo ve PSU ısısı kasa içi hava kadar önemlidir.",
        "Ne zaman servis?",
        "Fan tıkırtısı, şişen pil, yanık kokusu evde çözülmez. SSD doluysa bakım sihir değildir; dosya taşınır. RGB yazılımı arka planda 10 süreç açar; kapatmak toz kadar işe yarar.",
        "Yılda iki kez kapağı açmak",
        "Ofis PC’sinde yeter. Oyun kulesinde toz filtresi yıkanmadan macun konuşulmaz. Bakım vitrin FPS’i değil nefes alan kasadır.",
        ["Önce hava yolu", "Macunu her yıl değiştirmeyin", "Yanık kokusunda servis"],
        "Bilgisayar bakımı toz, termal macun ve kablodur. Yirmi numara listesi değildir.",
    ),
    "mobil-uygulamalarda-yapay-zeka-destekli-yeni-donem-basladi": e(
        "Hangi özellik yerelde kalır?",
        "Klavye tahmini ve fotoğraf bulanıklığı cihazdadır. Uzun sohbet ve büyük model buluttadır. ‘Yerel AI’ yazısı, fotoğrafın sunucuya gitmediği anlamına gelmeyebilir. Ayarlarda veri paylaşımı ve yedekleme ayrı kutulardır. Pil ve ısınma, NPU vaadinden önce gelir.",
        "Çevrimdışı test",
        "Uçak modunda özellik duruyorsa gerçekten yerelde. Durmuyorsa pazarlama. Ses asistanı komutları evdeki hoparlöre gidiyorsa gizlilik katmanı farklıdır. İş telefonunda bulut AI’yi kapatmak sızıntıyı keser.",
        "Küçük model, büyük iddia",
        "Telefondaki yapay zekâ hangi özelliğin yerelde kaldığıdır. Hepsi yerelde değildir.",
        ["Uçak modunda dene", "Fotoğraf yedekleme kutusunu oku", "İş telefonunda bulut AI’yi kapat"],
        "Yerel yazısı, verinin cihazdan çıkmadığı anlamına gelmeyebilir.",
    ),
    "yazilim-gelistiriciler-icin-yapay-zeka-destekli-araclar-yayginlasiyor": e(
        "Otomatik tamamlama, PR, sır",
        "Tamamlama herkese. PR özeti ekip içinde, müşteri sırrı modele değil. API anahtarı ve üretim logu sohbet geçmişine yapışmaz. Şirket kirası yoksa kişisel Copilot/ChatGPT iş reposuna bakmamalıdır. Önerilen yama, test olmadan merge edilmez.",
        "Lisans ve eğitim verisi",
        "Üretilen kodun lisansı belirsizse kapalı ürüne yapıştırma. Diff’i oku; üç satırlık ‘düzeltme’ bağımlılığı şişirebilir. CI kırmızısı model özgüveninden değerlidir.",
        "Sır ayrı kova",
        "Geliştirici yapay zekâsı tamamlama ve iskelettir. Üretim sırrı ve onaysız merge değildir.",
        ["Sırrı sohbete yapıştırma", "Şirket kirası yoksa iş reposunu kapama", "Önerilen yamayı testsiz merge etme"],
        "Araç hızdır. Sır ve test hâlâ sizin kapınızdadır.",
    ),
    "yapay-zeka-etiketi-uygulamalarda-daha-gorunur-olacak": e(
        "Etiket neyi söyler, neyi söylemez?",
        "‘AI ile üretildi’ rozeti, kaynağın doğru olduğunu kanıtlamaz. Sohbet özeti, otomatik altyazı ve yüz güzelleştirme ayrı şeylerdir. Kullanıcı hangi katmanın sentetik olduğunu görmezse etiket süs olur. Ayarlarda kapatılabilen etiket, şeffaflık değil isteğe bağlı dekorasyondur.",
        "Haber ve ödev",
        "Etiketli metin dipnot yerine geçmez. Uygulama mağazası açıklamasındaki AI rozeti, verinin nerede işlendiğini yazmaz. Çocuk uygulamasında etiket, ebeveyn paneli kadar işe yaramaz; varsayılan üretim kapalı olmalıdır.",
        "Rozet kaynak değildir",
        "Uygulamalarda yapay zekâ etiketi hangi katmanın sentetik olduğunu gösterirse işe yarar. Yoksa süslemedir.",
        ["Hangi katman sentetik bak", "Etiketi dipnot sanma", "Çocuk uygulamasında varsayılan üretimi kapat"],
        "Etiket şeffaflıktır. Doğruluk belgesi değildir.",
    ),
    "sirketler-musteri-hizmetlerinde-yapay-zeka-asistanlarini-deniyor": e(
        "Ne zaman insan, ne zaman taslak?",
        "Kargo nerede, çalışma saati, iade penceresi bota. Öfke, hukuki tehdit, sağlık ve ödeme itirazı insana. Bot ilk cevap taslağı üretir, gönderen insan olur. ‘Sizi anlıyorum’ kalıbı, 40 dakikalık bekleyişte yakar.",
        "Ölçüm",
        "İlk çözülme oranı ve insan devri. Devri artıyorsa bot yanlış yere konmuştur. Müşteri kaydını tüketici modele yapıştırma. Ses kaydı rıza ve saklama süresi olmadan eğitim verisi olmaz.",
        "İnsan tuşu her turda görünsün",
        "Müşteri hizmeti botu taslak ve SSS içindir. Şikâyet yönetimi değildir.",
        ["İnsan tuşu her turda görünsün", "Öfke ve ödemeyi bota bırakma", "Kaydı tüketici modele yapıştırma"],
        "Bot tekrarlayan soruyu keser. Tonda hata pahalıdır.",
    ),
    "haftanin-teknoloji-firsatlari-listelendi": e(
        "Sahte kupon, gri kutu, iade",
        "Haftalık fırsat listesi, fiyat geçmişi olmadan tuzak olur. Kupon kodu herkese açık forumda ölmüş olabilir. Gri kutu kamera aynı, garanti farklıdır. İade 14 gün, açılmış kulaklıkta bazen sıfırdır. ‘Bugün 23.59’ sayacı her gün sıfırlanır.",
        "Sepeti 24 saat beklet",
        "Aynı satıcı puanı ve IMEI/seri faturada yoksa geç. Kargo eşiği indirimi yer. Uzatılmış garanti ekranı kapsamıyorsa cam kadar işe yarar. Liste ezberi değil süzgeçtir.",
        "Fırsat, kasa anı değil iade günüdür",
        "Sahte kupon ve gri kutu kampanya dilini sever. Fatura ve servis ilini yaz.",
        ["Fiyat geçmişine bak", "Kuponu resmi sayfadan dene", "Faturada seri/IMEI"],
        "Haftalık fırsat listesi sepet, geçmiş ve iadedir. Yüzde değildir.",
    ),
    "robotik-sistemlerde-yapay-zeka-kullanimi-genisliyor": e(
        "İşyerinde güvenlik çemberi",
        "Görüntü tanıyan kol, çember ve acil stop olmadan ‘akıllı’ değildir. Pilot hat, yaya yolundan ayrı olmalıdır. Model güncellemesi gece vardiyasında sessizce davranışı değiştirir; sürüm kaydı yoksa kaza incelemesi kördür.",
        "Veri ve kamera",
        "Hat kamerası çalışan yüzünü de kaydeder. Rıza, saklama ve amaç yazılı değilse KVKK riskidir. Bakım robotu, kilitli alanda insan varken çalışmamalıdır. Demo videosu, tozlu gerçek hattın sürtünmesini göstermez.",
        "Çember, stop, sürüm",
        "İşyerinde robot + yapay zekâ güvenlik çemberidir. Vitrin kolu değildir.",
        ["Acil stop ve çember", "Sürüm kaydı tut", "Çalışan yüzünü amaçsız kaydetme"],
        "Robotik haberini güvenlik çemberi olmadan okuma.",
    ),
    "orta-segment-telefonlarda-fiyat-performans-yarisi-buyuyor": e(
        "Nerede para, nerede ödün?",
        "Para: güncelleme yılı, batarya, servis. Ödün: 120 Hz her zaman açık, 200 MP pazarlama, IP reklamı. Orta segmentte 3–5 yıl yama, üst segmentin 7 yılına yetişmez; bu ödündür, skandal değil. Gri ithal farkı serviste çıkar.",
        "Ekran ve şarj",
        "PWM hassasiyeti ve 80W kılıfla ısınma, vitrinde yok. 256 GB, 128 GB + bulut aboneliğinden ucuz olabilir. Kamera gece testi mağaza ışığında yapılmaz; sokağa çıkın.",
        "Yama yılı kasa farkından değerlidir",
        "Orta segment nerede para nerede ödündür. Megapiksel yarışı değildir.",
        ["Yama yılını oku", "Servis ilini yaz", "120 Hz’i her zaman açık sanma"],
        "Orta segment, üstün vitrin karesini kopyalamak zorunda değildir.",
    ),
    "yapay-zeka-iceriklerinde-guven-ve-dogrulama-daha-onemli-hale-geldi": e(
        "Üç kaynak kuralı",
        "Model cümlesi, resmi sayfa, üçüncü bağımsız kaynak. İkisi yoksa taslak. Tarih, sayı ve isim uydurma en sık kırılır. ‘Çalışmaya göre’ dipnotu tıklanmıyorsa yok say. Görseldeki yazı ve el sayısı hâlâ bozuktur.",
        "Haber ve sağlık",
        "Acil sağlık ve hukuk kararını modele bırakma. Ödevde uydurma makale faciasıdır. Şirket içi metni tüketici kutusuna yapıştırma. Filigran her zaman görünmez; süreç (kim onayladı) filigrandan önemlidir.",
        "Emin duruş kanıt değildir",
        "Yapay zekâ metnini doğrulama üç kaynak kuralıdır. Akıcı cümle değildir.",
        ["Üç kaynak", "Sayı ve tarihi resmi sayfadan tut", "Sağlık/hukuku modele bırakma"],
        "Güven, modelin özgüveni değil sizin tıklamanızdır.",
    ),
    "populer-uygulamada-arayuz-yenilemesi-basladi": e(
        "Menü yer değişince özellik kaybolmuş gibi görünür",
        "Arama kutusuna eski adını yaz. Büyük güncellemede varsayılan izinler sıfırlanabilir; konum ve mikrofonu tekrar kontrol et. Tema değişimi bildirimleri az göstermez; sessize aldığın kanal hâlâ oradadır. Yedek almadan ‘eski haline dön’ butonu her uygulamada yoktur.",
        "İş hesabı ve tema",
        "Şirket profili yeni arayüzü geç zorunlu kılabilir. Kişisel ve iş hesabını karıştırma. Eski kısayol kaybolduysa resmi yardım sayfası, sosyal medya öfkesinden hızlıdır. Güncelleme notundaki ‘daha sade’ cümlesi üç tıklama eklemiş olabilir.",
        "İzinleri tekrar oku",
        "Arayüz yenilenince yapılacak ilk iş kayıp sandığın özelliği aramak ve izinleri kontrol etmektir. Panik silmek değildir.",
        ["Eski özellik adını ara", "Konum ve mikrofon izinlerini kontrol et", "Yedek almadan hesap silme"],
        "Yeni arayüz kayıp özellik değildir. Önce ara, sonra öfkelen.",
    ),
    "sarj-teknolojileri-daha-guvenli-ve-hizli-hale-geliyor": e(
        "Watt, kablo, ısınma, sahte kafa",
        "Kutu 120W yazar, kablo 60W taşır. USB-C kabloda e-marker yoksa ısınır. Sahte kafa prizden kıvılcım ve şişen pil üretir. Standart (PD) yazısı, her kafa her telefonla 100W demek değildir. Kılıf içinde hızlı şarj ısı tuzağıdır.",
        "Gece prizi",
        "Yastık altında telefon ve kafa yangın senaryosudur. 80–85’te kesen yazılım yoksa priz zamanlayıcısı ucuzdur. Uçak ve otel USB’si veri sızdırabilir; şarj-only kablo işe yarar. Islak elle watt yarışı yapılmaz.",
        "Kablo ve kafa resmi listede mi?",
        "Hızlı şarj dakikayı kurtarır. Sahte kafa ve ısı kimyayı yer.",
        ["Kablo e-marker", "Sahte kafa alma", "Yastık altında şarj yok"],
        "Şarj haberi watt tablosu değil kablo, ısı ve sahte kafadır.",
    ),
    "laptoplarda-yapay-zeka-islemcileri-daha-fazla-kullanilacak": e(
        "NPU kime lazım?",
        "Gürültü engelleme, altyazı ve yerel küçük model NPU’yu yer. 4K kurgu ve AAA oyun hâlâ GPU/CPU işidir. NPU TOPS sayısı, sürücü ve uygulamanın o birimi kullandığı anlamına gelmez. Görev yöneticisinde NPU satırı yoksa vitrin TOPS’udur.",
        "Pil ve Windows Studio",
        "Kamera bulanıklığı NPU’da ucuz, GPU’da ısınır. Linux’ta NPU sürücüsü geç gelebilir. 16 GB lehimli RAM, yerel model + tarayıcı için daralır. Toplantı ve altyazı için NPU işe yarar; ‘yapay zekâlı laptop’ her işi hızlandırmaz.",
        "Uygulama gerçekten NPU kullanıyor mu?",
        "Yapay zekâ işlemcili dizüstü NPU kime lazım sorusudur. TOPS tablosu değildir.",
        ["Görev yöneticisinde NPU var mı bak", "RAM 32 GB düşün", "Kurgu/oyun için GPU’yu ayrı say"],
        "NPU toplantı ve küçük yerel model içindir. Her iş için değildir.",
    ),
    "kamera-odakli-akilli-telefonlar-sosyal-medya-kullanicilarini-hedefliyor": e(
        "Işık, renk, dosya",
        "Sosyal medya 1080p ve sıkıştırma yer. 200 MP dosyası hikâyede görünmez; ışık ve renk profili görünür. Gece modu 3 saniye tutmayı ister. Log çekim, uygulama içi filtreyle bozulur. Ham dosya yedeklenmezse ‘profesyonel kamera’ bir akşamlık olur.",
        "Ön kamera ve ısınma",
        "Canlı yayın ısındırır ve pil yer. Stabilizasyon yürüyüşte işe yarar, koşuda rüzgâr sesi kalır. Renk bilimi markadan markaya kayar; iki telefonla çekilen seri aynı hikâyede kırılır. Depolama 256 GB, 4K rulo için 128’den değerlidir.",
        "Hikâye için megapiksel değil ışık",
        "Sosyal medya kamerası ışık, renk ve dosyadır. Vitrin karesi değildir.",
        ["Gece testini sokakta yap", "Ham yedek al", "İki telefon renklerini karıştırma"],
        "Kamera odaklı telefon, hikâyenin ışığı ve yedeğidir. Megapiksel yarışı değildir.",
    ),
    "gelisim-ekipleri-icin-yeni-kodlama-araclari-tanitildi": e(
        "Ekibe alma kontrol listesi",
        "Lisans, veri nereye gidiyor, offline çalışıyor mu, lockfile ile uyumlu mu, fiyat koltuk mu token mı. Demo stüdyo reposuyla çalışır; sizin monorepo’nuzda kırılır. SSO ve denetim kaydı yoksa şirket standardı olamaz. ‘AI kodlar’ cümlesi test kapsamını silmez.",
        "Geçiş maliyeti",
        "Eski kısayol ve snippet bir hafta yer. Araç değişimi 10 sağlam testi taşımıyorsa geçmeyin. Öğrenci için ücretsiz katman, iş için ayrı kira. Üretilen kodun lisansı belirsizse kapalı ürüne yapıştırma.",
        "Sır ve PR",
        "Yeni kod aracı ekibe alma listesidir. Vitrin hızı değildir.",
        ["Lisans ve veri bölgesi", "SSO yoksa şirket standardı yapma", "10 testi taşıyamıyorsa geçme"],
        "Yeni araç, listenizdeki sır, lisans ve testten sonra gelir.",
    ),
    "e-spor-turnuvalarinda-final-haftasi-heyecani-basladi": e(
        "Final haftasını izlerken bilinmesi gerekenler",
        "Format (BO3/BO5), patch sürümü ve kadro değişimi skoru okur. Bahis ve ‘kesin olur’ dili AcarTechs’te yok. Yayın gecikmesi 30–90 saniye; sosyal medya spoiler’ı yayından önce gelir. Çocuk profilinde chat kapatılır. Resmi yayın ile korsan overlay aynı maç değildir.",
        "Patch ve kadro",
        "Finalden bir gün önce gelen denge yaması, grup aşaması formunu sıfırlar. Yedek oyuncu, ‘aynı kadro’ cümlesini bozar. VOD ertesi gün, gece 3 maçından değerlidir. Bahis reklamı yayın içine gömülür; kapatmak izleyici işidir.",
        "Spoiler ve gecikme",
        "Final haftası format, patch ve spoiler süzgecidir. Slogan değildir.",
        ["Patch notunu oku", "Yayın gecikmesini unutma", "Chat’i çocuk profilinde kapat"],
        "E-spor finali form ve yama ile okunur. Afişle değil.",
    ),
    "konsol-oyunculari-icin-sistem-guncellemesi-yayinlandi": e(
        "Güncelleme gelince kontrol listesi",
        "Depolama %20 boş mu, indirme geceye alındı mı, oyun içi ses ve parti sohbeti kırıldı mı. Beta/insider halkası ürün vaadi değildir. Zorunlu güncelleme, yarınki çok oyunculu maçı kilitleyebilir; akşam 18.00’de başlatmayın. Kaydedilen veri buluta gidiyor mu bak; gitmiyorsa yedek al.",
        "Sosyal özellik ayrı, güvenlik yaması ayrı",
        "Yeni emoji, çekirdek yamayı geciktirmek için bahane değildir. Çocuk hesabında yeni paylaşım varsayılanını kapat. İkinci el konsolda güncelleme, önceki hesabın kalıntısını göstermez; fabrika ve ağ şifresi ayrı iştir.",
        "Gece indir, gündüz oyna",
        "Konsol güncellemesi kontrol listesidir. Sosyal vitrin değildir.",
        ["Depolama boşluğu", "Akşam maçından önce başlatma", "Bulut kayıt açık mı bak"],
        "Sistem güncellemesi yama ve depolamadır. Emoji değildir.",
    ),
    "yeni-cikacak-aksiyon-oyunu-icin-ilk-oynanis-videosu-geldi": e(
        "Kameradan gerçeğe",
        "90 saniyelik montaj, 40. dakikadaki tekrar döngüsünü gizler. HUD kapalı çekim, piyasadaki arayüzü göstermez. 30 fps kayıt 60 fps vaadi değildir. Demo yoksa oynanış videosu davettir, ölçüm değildir. Ön sipariş, ikinci video ve süre tahmininden sonra gelir.",
        "Ses ve kesik",
        "Müzik hilesi ses kapalı izlemede ele gelir. ‘Dünya prömiyeri’ tarihi pencereyse takvime belirsiz yaz. Performans hedefi (4K 60) hangi modelde yazıyor bak; giriş modeli ayrı cümledir.",
        "İkinci videoyu bekle",
        "Oynanış videosu kameradan gerçeğe süzgeçtir. Satın alma emri değildir.",
        ["HUD kapalı çekimi piyasa sanma", "Ön siparişi ikinci videoya bırak", "Hangi konsol modeli yazıyor bak"],
        "İlk oynanış davettir. 12 saatlik tempo kanıtı değildir.",
    ),
    "hayatta-kalma-oyunlarinda-yeni-sezon-icerikleri": e(
        "Neyi sıfırlar, neyi tutar?",
        "Sezon geçişi savaş bileti, sıralama ve bazı kaynakları sıfırlar. Kozmetik ve ev içi dekor çoğu zaman kalır. ‘Her şey silindi’ paniği, yama notunu okumadan atılır. Yeni harita eski rotayı öğretir; ilk hafta ranked değil alışma.",
        "Savaş bileti matematiği",
        "Sezonun kalan günü × günlük XP, bileti bitirmeye yetmiyorsa para gömmeyin. Event silahı FOMO’su, sonraki sezonda kasa fiyatına döner. Sunucu doluluğu ilk 72 saatte yalan söyler; üçüncü hafta asıl nüfustur.",
        "Yama notu önce",
        "Hayatta kalma sezonu neyi sıfırlar neyi tutar sorusudur. Her şeyi silme paniği değildir.",
        ["Yama notunda sıfırlananı oku", "Bilet matematiği yap", "İlk hafta ranked’e girmek zorunda değilsin"],
        "Sezon geçişi FOMO değil yama notu ve XP matematiğidir.",
    ),
    "haftanin-oyun-firsatlari-ve-ucretsiz-yapimlari-aciklandi": e(
        "Resmi mağaza, süre notu, depolama",
        "Ücretsiz yazısı resmi mağaza ve süre bitişi olmadan tuzak olur. Epic/Steam/konsol anahtarı üçüncü site, çalıntı hesap satar. 80 GB indirme, 2 saatlik deneme için pahalıdır. Aile payaşımında ‘ücretsiz’ bir koltuğa bağlı kalabilir.",
        "Kütüphaneye ekle, hemen indirme",
        "Süre bitmeden eklemek yeter; disk sonra. Çocuk hesabında harcama onayı kapalı olsun. ‘Sınırsız ücretsiz’ haftası, üç ay oynamayacağın 12 oyunu indirir; sonra güncelleme kuyruğu doğar.",
        "Süre ve kaynak",
        "Ücretsiz ve indirimli oyun resmi mağaza, süre ve depolamadır. Forum kodu değildir.",
        ["Resmi mağaza", "Süre bitişini yaz", "Hemen indirmek zorunda değilsin"],
        "Fırsat listesi keşif aracıdır. Diski doldurma emri değildir.",
    ),
    "xbox-insiders-icin-gamertag-oyun-merkezi-ve-istek-listesi-guncellemeleri-geldi": e(
        "Test özelliğini ne zaman ciddiye almalı?",
        "Insider halkası ürün vaadi değildir. Gamertag ve istek listesi deneyi, yarınki aile hesabında kırılabilir. Çok oyunculu maç öncesi beta kanalına geçmeyin. Geri bildirim hub’ı resmi yol; sosyal medya öfkesi değil. Özellik ring’de görünmüyorsa ‘bende yok’ skandalı değildir.",
        "Yedek ve çıkış",
        "Insider’dan çıkmak güncellemeyi geri almayabilir. Çocuk hesabını beta’ya almayın. Test notundaki ‘gelebilir’ fiili takvime işlenmez.",
        "Halka ≠ vitrin",
        "Xbox Insider güncellemesi test özelliğidir. Satın alma gerekçesi değildir.",
        ["Maç öncesi beta’ya geçme", "Çocuk hesabını halkaya alma", "Gelebilir fiilini takvime yazma"],
        "Insider ciddiye alınır, ürün gibi satılmaz.",
    ),
    "xbox-22-26-haziran-haftasinda-cikacak-yeni-oyunlari-listeledi": e(
        "Kısa pencere, seçici indirme",
        "Haftalık çıkış listesi alışveriş fişi değildir. Cihaz, Game Pass katmanı ve 20 saatlik gerçek süre süzgecidir. 100 GB’lık üç oyun aynı hafta, 512 GB konsolu tıkar. Listeye girmek her başlığın sizin türünüz olduğu anlamına gelmez.",
        "Katman ve dil",
        "Core/Essential ile Ultimate aynı kapı değildir. Dil ve bulut kayıt notunu mağaza sayfasından oku. Haftalık liste keşif aracıdır; FOMO takvimi değildir.",
        "Bir oyun seç, ikincisini istek listesine bırak",
        "Haziran sonu Xbox takvimi kısa pencere ve seçici indirmedir.",
        ["Katmanı kontrol et", "Depolamayı say", "Üçünü birden indirme"],
        "Haftalık liste süzgeçtir. Tamamını indirme emri değildir.",
    ),
    "nintendo-direct-switch-2-icin-yeni-oyunlari-ve-klasik-donusleri-duyurdu": e(
        "Direct sonrası alışveriş listesini sadeleştir",
        "90 dakikalık yayın 12 ön sipariş üretmek zorunda değildir. Tarih pencere, remake ve yeni IP’yi ayır. Klasik dönüş, orijinal kartuşu çöpe atmayı gerektirmez. Direct anı fiyatı, bir hafta sonraki sakin etiketle aynı olmayabilir.",
        "Stok ve hesap",
        "Nintendo hesabı bölgesi, eShop bakiyesi ve aile grubu ön siparişten önce gelir. ‘Direct’te gördüm’ tek başına stok garantisi değildir. Çocuk hesabında harcama pimi.",
        "Üç başlık kuralı",
        "Bu yıl bitecek üç oyun yaz, gerisini istek listesine al. Direct vitrindir. Cüzdan emri değildir.",
        ["Tarih pencereyse belirsiz yaz", "Hesap bölgesini kontrol et", "Üç başlık kuralı"],
        "Nintendo Direct sonrası liste sadeleştirilir. Tamamı alınmaz.",
    ),
    "mobil-oyunlarda-grafik-kalitesi-hizla-artiyor": e(
        "Grafik ve pil: ayarları nasıl dengelemeli?",
        "Ultra gölge 10 dakikada ısınır ve kare düşer. 60 fps seçeneği 30 fps + yüksek çözünürlükten rekabetçi oyunda değerlidir. Wi-Fi indirme paketi, hücreselde 4 GB yer. Çocuk tabletinde ultra varsayılanı kapat. Soğutma kılıfı mucize değil; 20 dakika ara ver.",
        "Pil ve mağaza",
        "Savaş bileti ve ‘sınırlı kaplama’ grafik ayarından ayrı faturadır. Düşük grafik, rekabetçi nişanda avantaj olabilir. Isınan cihazı ‘şarjı bitmiş’ diye kapatmayın; ayarı düşürün.",
        "Vitrin karesi seans konforu değildir",
        "Mobil oyunda grafik ve pil ayar dengesidir. Mağaza karesi değildir.",
        ["Ultra’yı varsayılan bırakma", "Hücreselde indirme paketini kapat", "Isınınca ayarı düşür"],
        "Grafik kalitesi ısınma, kare ve pil ile ölçülür.",
    ),
    "xbox-games-showcase-2026-oyun-dunyasinda-yeni-duyurularla-tamamlandi": e(
        "Duyurudan sonra ne takip edilmeli?",
        "Fragman ezberi değil tarih, cihaz ve Game Pass notu. Pencere tarih takvime belirsiz yazılır. ‘Xbox’ta gelir’ bulut, konsol ve PC’yi aynı kapı sanmaz. Showcase anı stok ve ön sipariş paniğidir; resmi sayfa bir gün sonra daha sakin olur.",
        "Hangi başlık sizin 40 saatiniz?",
        "Üç duyuru seç, gerisini istek listesine al. Performans hedefi hangi modelde yazıyor bak. Çocuk hesabında showcase yayını spoiler ve bahis reklamı taşıyabilir.",
        "Tarih, cihaz, katman",
        "Showcase sonrası takip bu üçüdür. Fragman karesi değildir.",
        ["Tarih pencereyse belirsiz yaz", "Game Pass notunu oku", "Üç başlık seç"],
        "Showcase vitrindir. Kütüphane planı süzgeçle yapılır.",
    ),
    "halo-campaign-evolved-temmuzda-oyuncularla-bulusmaya-hazirlaniyor": e(
        "Tarih, platform, kim için mantıklı?",
        "Remake/Evolved, orijinal kampanyayı bitirmiş oyuncuya nostalji, yeni oyuncuya giriş kapısıdır. İkisi aynı mağaza sayfasında durur, aynı ihtiyaç değildir. Çok oyunculu vaadi kampanya tarihinden ayrı cümledir. Depolama ve 120 fps hangi modelde yazıyor bak.",
        "Game Pass ve kutu",
        "Katmanda varsa kutu fiyatı keşif içindir. Yoksa kampanya süresi (kaç saat) ve kooperatif notu karar verir. Temmuz penceresi, tam gün netleşmeden izin günü bağlamaz.",
        "Nostalji ayrı, giriş ayrı",
        "Halo Campaign Evolved tarih, platform ve kim için mantıklı sorusudur. Afiş değildir.",
        ["Model ve fps notunu oku", "Katmanda mı bak", "Kampanya süresini say"],
        "Evolved, herkese aynı anda zorunlu değildir.",
    ),
    "xbox-wire-20-24-temmuz-haftasinin-yeni-oyunlarini-duyurdu": e(
        "Haftalık Xbox çıkış listesi nasıl kullanılır?",
        "Alışveriş fişi gibi değil cihaz ve süre süzgeciyle. 20–24 Temmuz penceresi üç büyük indirmeyi 512 GB’da taşımaz. Tür ve seans: 30 dakikalık indie ile 40 saatlik kampanya aynı ihtiyaç değildir. Cloud’da dene, beğenirsen indir.",
        "Aile ve çocuk",
        "Yaş etiketi ve harcama pimi liste heyecanından önce gelir. Haftalık Wire keşiftir. FOMO takvimi değildir.",
        "Bir indir, iki istek listesi",
        "Haftalık çıkış listesi süzgeçtir. Tamamını indirme emri değildir.",
        ["Depolamayı say", "Cloud’da dene", "Yaş etiketini oku"],
        "Wire listesi keşif aracıdır. Disk doldurma emri değildir.",
    ),
    "oyuncu-ekipmanlarinda-fiyat-performans-secimleri": e(
        "Mouse, kulaklık, klavye",
        "Sensör DPI vitrini, ağırlık ve kavrama kadar önemli değildir. Kulaklıkta mikrofon ve konfor, 7.1 yazısından önce gelir. Mekanik anahtar, ofis komşusunda tıkırtıdır; sessiz anahtar işe yarar. RGB yazılımı ikinci bir hesap ve arka plan sürecidir.",
        "Kablo ve yedek",
        "Kablosuz 2.4 GHz, Bluetooth gecikmesinden ayrıdır. Yedek piller ve yedek switch, ‘pro’ etiketinden değerlidir. İkinci el mouse taban aşınması, sensör kadar oyunu bozar.",
        "Önce kavrama ve konfor",
        "Oyuncu ekipmanında fiyat/performans vitrin ışığından önce bakılacaklardır.",
        ["Mouse’u elde dene", "Kulaklıkta mikrofonu dene", "RGB yazılımını zorunlu sanma"],
        "Ekipman vitrin FPS’i değil ağırlık, konfor ve yedektir.",
    ),
    "bagimsiz-oyunlar-yaratici-fikirleriyle-one-cikiyor": e(
        "Kısa seans, niş tür, düşük pişmanlık",
        "Demo, süre tahmini ve iade penceresi riski düşürür. Erken erişim, 1.0 vaadi değildir. Niş tür (bulmaca, kısa anlatı) 12 saatlik aksiyon ihtiyacını doldurmaz. İstek listesi, indirim ve demo bitince alın.",
        "Küçük ekip, büyük yama",
        "Launch haftası kırık kayıt, bir ay sonra düzelir. Steam yorumunu son 30 gün ve dil notuyla oku. ‘Bağımsız’ etiketi kalite belgesi değildir; süzgeçtir.",
        "Demo yoksa küçük miktar",
        "Bağımsız oyun seçme rehberi düşük pişmanlıktır. Liste ezberi değildir.",
        ["Demo oyna", "Süre tahminine bak", "Erken erişimi 1.0 sanma"],
        "Indie keşfi riski küçültmektir. Her başlığı almak değildir.",
    ),
    "oyuncu-bilgisayarlarinda-ekran-karti-secimi-yeniden-gundemde": e(
        "1080p, 1440p, 4K gerçeği",
        "Önce monitör. 1080p 60 Hz’de üst segment kart ısınır ve para yer. 1440p 144 Hz orta-üst denge. 4K, PSU, kasa hava ve CPU darboğazı olmadan vitrin FPS’idir. DLSS/FSR, native 4K vaadi değildir; tercih yazılır.",
        "Watt ve 24 ay",
        "Eski 550W PSU yeni kartı keser. Dar kasa 3 fanı kısar. Faturasız ikinci el madencilik taşır. RAM 32 GB 2026’da varsayılandır.",
        "Monitör → kart → PSU",
        "Oyuncu PC’sinde ekran kartı bu sıradır. Tersi israftır.",
        ["Önce monitör", "PSU watt", "Faturasız ikinci eli işe koyma"],
        "Kart seçimi çözünürlük, watt ve 24. aydır. Slayt FPS’i değildir.",
    ),
    "playstation-plus-haziran-katalogunda-final-fantasy-xvi-one-cikti": e(
        "Extra/Premium kime yeter?",
        "Essential aynı kataloğu açmaz. FFXVI uzun kampanya, Sonic kısa tempo, Kingdom Come yavaş simülasyon, Life is Strange bölüm bölümdür. Aynı ayda durmaları aynı hafta bitirme zorunluluğu değildir. 15 saat ayırabileceğiniz bir kampanya seçin, ikincisini kısa seansa bırakın.",
        "Depolama ve ‘hepsini indir’",
        "Kullanılmayan 100 GB ucuz değildir. Seriyi bitirmiş oyuncu için FFXVI haber değeri düşüktür; Sonic veya Kingdom Come daha çok hizmet eder. Çıkış tarihi geçmiş AAA, yeni oyuncu çekme yoludur.",
        "Katmanı kendi faturanla çarp",
        "Plus haberi katman, süre ve depolamadır. İsim listesi değildir.",
        ["Katmanını kontrol et", "Bir kampanya seç", "Hepsini indirme"],
        "Katalog değeri kullanılmayan indirme ile ölçülmez.",
    ),
    "oyun-abonelik-servislerine-yeni-yapimlar-eklendi": e(
        "Game Pass mi PlayStation Plus mı?",
        "Cihaz, katman ve haftalık oyun süresi karar verir. İki evi iki konsol, iki faturadır. PC + konsol Game Pass Ultimate kapısıdır; yalnızca TV önü Plus veya Game Pass Core başka hesaptır. Katalog her ay değişir; ‘kütüphanem’ sanmak, çıkan oyunu kaybettirir.",
        "Bu ay 15 saat",
        "İki aboneliği birden tutmak günde 2 saat oynayan ev için israftır. Ayın yıldızı hangisindeyse o açılır. Çocuk hesabı harcama pimi ve yaş katmanı, katalog heyecanından önce gelir.",
        "Cihaz + süre + katman",
        "2026 abonelik rehberi bu üçüdür. İsim listesi değildir.",
        ["Cihazını yaz", "Haftalık saati yaz", "İki aboneliği varsayılan tutma"],
        "Abonelik, cihaz ve süreyle seçilir. Her iki kapı birden zorunlu değildir.",
    ),
    "xbox-game-pass-temmuz-listesine-yeni-oyunlar-ekleniyor": e(
        "Katalogdan nasıl seçilir?",
        "Temmuz listesi alışveriş fişi değildir. Tür, seans, depolama. Day One yazısı, gün-bir yama kuyruğunu gizlemez. Cloud ile 20 dakika dene, beğenirsen indir. Çıkan oyunlar için bitirme tarihi yaz; katalogdan düşme sürprizi yapar.",
        "Core ile Ultimate aynı kapı değil",
        "Aile grubunda kimin katmanı hangi oyunu açar bak. 3×100 GB aynı hafta 512 GB’ı tıkar. Liste keşiftir. Tamamını indirme emri değildir.",
        "Dene, seç, indir",
        "Game Pass temmuz listesi süzgeçtir. FOMO takvimi değildir.",
        ["Cloud’da dene", "Katmanı kontrol et", "Çıkış tarihini yaz"],
        "Katalogdan seçmek, listedeki her başlığı indirmek değildir.",
    ),
    "xbox-konsol-fiyatlarinda-agustos-itibariyla-yeni-donem-basliyor": e(
        "512 GB, 1 TB, 2 TB sonlanması",
        "Depolama kararı takvim işidir. 1 Ağustos öncesi 2 TB bakiyesi, Game Pass kütüphanesi şişen ev için anlamlıdır. 512 GB, harici disk veya sürekli sil-yükle demektir. İkinci el fiyatı etiket değişince kayar; acele satmak da acele almak da cezadır.",
        "Şimdi mi sonra mı",
        "Oyun takviminiz 3 aydır boşsa zam paniği alım gerekçesi değildir. Tamir ve garanti, gri kutu indiriminden değerlidir. Dijital-only ile disk sürücülü model, kütüphane alışkanlığınıza bağlıdır.",
        "Depolama ve tarih",
        "Xbox konsol fiyatı değişince yapılacak ilk iş depolama ihtiyacını ve 1 Ağustos takvimini yazmaktır.",
        ["Depolama ihtiyacını yaz", "2 TB sonlanma tarihini işaretle", "Gri kutuyu zam paniğine bağlama"],
        "Etiket değişimi, depolama ve zamanlama kararıdır. Panik değildir.",
    ),
    "xbox-wire-temmuz-ayi-indie-selects-listesini-yayimladi": e(
        "Tür, seans, erişim",
        "Aynı seçkide bulmaca ve 12 saatlik hikâye yan yana durabilir. Game Pass’te mi ayrı satış mı bak. Yaz döneminde 30 dakikalık deney ile uzun anlatı aynı ihtiyaç değildir. Dil ve kayıtlama notunu mağaza sayfasından oku.",
        "Keşif maliyeti",
        "Seçkiye girmek her cihazda aynı performansı vaat etmez. Kısa seans ve abonelikle yöneten oyuncu için maliyet düşüktür. Yalnızca rekabetçi çok oyunculu arayan için listenin tamamı zorunlu değildir.",
        "Üç filtre olmadan ‘kaçırma’ yazma",
        "Indie Selects keşif aracıdır. Ödül töreni değildir.",
        ["Türü ayır", "Erişim modeline bak", "Süreyi say"],
        "Temmuz seçkisi keşiftir. Her başlık zorunlu değildir.",
    ),
}

